### ISSUE TITLE
I want to add a GRB LED on the pi, what should I do?

### ISSUE THREAD

**Issue by phucdat55** [OpenStickCommunity/GP2040-CE#1013]
> Please read these quoted sections before submitting, and remove them (including this one) when you have provided what
> is asked, in order to make addressing the issue easier for everyone. Thank you!
>
> Be sure to:
> * Check the documentation [HERE](https://gp2040-ce.info/) to answer many questions on hardware requirements and usage.
> * Make sure that your issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues).

### Expected Behavior

> Please describe the behaviour you are expecting.

### Current Behavior

> What is the current behaviour? If this is something that worked in the past, be sure to include the conditions in
> which it did.

### Context

> Please provide all relevant information about your setup. This is important in case the issue is not reproducible
> except under certain conditions. Important elements include:
>
> * Name of device
> * Link to where you purchased the device
> * Firmware version
> * Available schematics, designs, etc., especially for custom hardware
> * Similar hardware (e.g. if it has the same GPIO-to-button assignments as a Pico)

### Steps to Reproduce

> Please provide detailed steps for reproducing the issue.
>
> 1. Step 1
> 2. Step 2
> 3. ETC...

### Screenshots & Files

> Please include any relevant screenshots or files here, including photos of the front and back of the board.

**Comment by TheTrainGoes** [comment]
Hi @phucdat55 there is no info provided in this.  Please add the requested info.
