### ISSUE TITLE
Rotary encoder

### ISSUE THREAD

**Issue by luckyaa35** [OpenStickCommunity/GP2040-CE#1027]
i dont find PIN where i need connect my rotary encoder (VCC, DATA, CLK, GND). I use RPI PICO

Thanks for you help

**Comment by TheTrainGoes** [comment]
Hi @luckyaa35 ,

Please spend some time on our information site and read up in the web-config section.  All of this is covered there.

https://gp2040-ce.info/add-ons/rotary-encoders

**Comment by TheTrainGoes** [comment]
Only the ADC pins will work - 26,27 or 28

**Comment by luckyaa35** [comment]
Thanks

**Comment by mikepparks** [comment]
@TheTrainGoes That's not correct. The rotary encoder is not dependent on analog pins to function.

**Comment by TheTrainGoes** [comment]
Apologies - All pins it is.
