### ISSUE TITLE
Missing labes for localization

### ISSUE THREAD

**Issue by rebornsick** [OpenStickCommunity/GP2040-CE#1037]
### Problem

There are some lables that needs to be translated.

#### SettingsPage

- sections on the left

<img width="364" alt="Snipaste_2024-06-04_09-00-26" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/28842872/ea6a3c7a-fd1f-48b6-8615-54c91c0c1e29">

- hotkey-actions.next-profile option seems not have a proper name yet.

<img width="107" alt="Snipaste_2024-06-04_09-01-58" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/28842872/61da0e5c-c2af-44eb-b34d-aeeb1afd56fc">

#### DisplayConfig

- options of Flip Display

<img width="245" alt="Snipaste_2024-06-04_09-05-57" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/28842872/44981f7b-6e84-47bc-a980-5baa882cd7f6">

#### AddonsConfig

- options of On Board LED config

<img width="327" alt="Snipaste_2024-06-04_09-06-15" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/28842872/23e7863c-103b-4a18-9983-9d07803dd89c">

- options of Joystick Selection Slider

<img width="235" alt="Snipaste_2024-06-04_09-06-49" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/28842872/8476da48-36ce-4f22-934e-9b28a254042b">

- options of DDI Dual D-Pad Mode and Combination Mode

<img width="472" alt="Snipaste_2024-06-04_09-07-30" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/28842872/6e3d404e-7e95-4abd-a437-0bf52191a5f2">

- options of SOCD Slider Mode Default

<img width="234" alt="Snipaste_2024-06-04_09-07-59" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/28842872/a801be65-3233-4a8c-903a-4fc41d553a9e">

- Lock Macro in Focus Mode Configuration

<img width="477" alt="Snipaste_2024-06-04_09-09-00" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/28842872/b8323130-c8a5-43b2-83fc-6d75bb6cee7e">

#### InputMacroAddon

- Macro name and Activation Type

<img width="164" alt="Snipaste_2024-06-04_09-11-01" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/28842872/7aa3bfba-b611-4d69-be1c-6b2b61c679e5">

### Solution

would love to see these lables added in the future.

and if we can set options like "D-Pad", "Digital", "Left Analog", "Right Analog" as universal lables since many selections have these same options.

### Do you plan to work on this feature yourself?

I'd love to but no, it's out of my ability.

**Comment by SavageCore** [comment]
Thanks for this!

Lock Macro in Focus Mode Configuration is under Common.jsx `lock-macro`

See `Data/Addons.ts` for universal labels.

**Comment by rebornsick** [comment]
I missed that one, so I need to wait for your PR to be merged before I can complete the localization. Then my PR can be merged, right? I’m not very clear about this process.

**Comment by SavageCore** [comment]
Yes that will be ideal, there's more missing translations for us to go through.
