### ISSUE TITLE
FEATURE REQUST: automatic detection of all platform and automatic switch to that mode

### ISSUE THREAD

**Issue by starkyghayas** [OpenStickCommunity/GP2040-CE#1053]
hi can you please add automatic detection of which platform on playing example if I am playing on PS5 my controller should automatically switch to PS 5 mode or if I am playing on Xbox 360 or PS 4 or switch or PC it should switch automatically to that mode if it's possible please add to 2040ce firmware thanks

**Comment by TheTrainGoes** [comment]
Going to close this request out - we have no plans to introduce auto-detection at this time.
