### ISSUE TITLE
The 8-minute timeout issue using GP2040-CE_0.7.9_Haute42COSMOX.uf2 in PS5

### ISSUE THREAD

**Issue by joselitofilho** [OpenStickCommunity/GP2040-CE#1077]
### Expected Behavior

After the 8-minute timeout, my haute42 doesn't disconnect.

### Current Behavior

1. Plug your controller into the PS4/5
1. Press the PS button to initialize the controller
1. Play for roughly 8 minutes
1. Console rejects the controller due to failed authentication
1. User unplugs their non-functional controller
1. Go back to step 1 and repeat

### Context

* Firmware version: GP2040-CE_0.7.9_Haute42COSMOX.uf2
* Name of device: Haute 42, HautePad T16
* Link to where I purchased the device: https://www.amazon.com/dp/B0CN6M44F4?psc=1&ref=ppx_yo2ov_dt_b_product_details
* http://192.168.7.1/settings:
<img width="1727" alt="image" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/1102589/94dc3e01-a455-4b96-9634-7bc6c77ce1f9">
* http://192.168.7.1/settings:
<img width="1718" alt="image" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/1102589/aad1d84f-95c8-48f4-9d45-13778e1ffbc0">
<img width="1717" alt="image" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/1102589/20b983ee-12b1-41dc-9ec9-c3a210dbcbad">
<img width="1714" alt="image" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/1102589/9f612699-19e7-41f5-89c7-53919c0f0c3f">
<img width="1709" alt="image" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/1102589/0644798d-4586-48a9-bb51-13d6de0b131f">
<img width="1715" alt="image" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/1102589/260e9362-cc46-4142-9043-e022036080af">

### Steps to Reproduce

1. Plug haute42 on PS5
2. Wait 8 minutes

**Comment by arntsonl** [comment]
Please read our documentation first on PS4 and PS5. You must have a supported dongle such as the Haute42 Booter 5 plugged into your device.

https://gp2040-ce.info/faq/faq-console-compatibility#playstation

**Comment by joselitofilho** [comment]
@arntsonl , how can I use my PS5 controller to authenticate my GP2040-CE device?

**Comment by TheTrainGoes** [comment]
Removing this thread
