### ISSUE TITLE
4th button of the microswitches on Flatbox rev5 does nothing

### ISSUE THREAD

**Issue by Soundtoxin** [OpenStickCommunity/GP2040-CE#108]
I have built several flatboxes now and this button (4th from the left, or 1st of the second grouping of 3 buttons) never seems to do anything on the gamepad-tester site. Every other button works. Is it a console-only button or something? I have not had a chance to test on a PlayStation yet.

**Comment by TheTrainGoes** [comment]
Hi @Soundtoxin ,

This is mapped to the capture button which is really only on the Nintendo Switch.   

You can remap it to another function like turbo or any of the other cool add-ons we have in the webconfig.   

Closing this as it is expected behavior.

**Comment by Soundtoxin** [comment]
Thanks, that's good to know!
