### ISSUE TITLE
Left(Right) Analog Stick X+Y added to Rotary Encoders Control Mode.

### ISSUE THREAD

**Issue by irorichan** [OpenStickCommunity/GP2040-CE#1082]
I would like to use a rotary encoder to play Forgotten Wolrds(Capcpm Arcade Stadium).
In the current setup, I have one analog stick x-axis and one analog stick y-axis each controlling one of them, 
but I want it to be mapped on the circumference by controlling the x-axis and y-axis of the analog stick at the same time.

**Comment by TheTrainGoes** [comment]
Hi @irorichan ,

I had to grab a copy of the game to see how they implemented the spinner.  On the Switch version its either mapped to an absolute analog value (where the rotation stops based on your analog position), or, more true to how the original worked where there is a free-spin that simply rotates either clockwise or counterclockwise.  

What I would recommend you do is map it as left and right trigger in the web-config options under rotary encoder and then switch the config in game to be the same.  

This will make it feel more like the original.
