### ISSUE TITLE
Enabling an Addon > changing config > disabling the addon> and saving does not save the new config

### ISSUE THREAD

**Issue by SolidwareGit** [OpenStickCommunity/GP2040-CE#1091]
### Expected Behavior

When enabling an add-on, making a change to the add-on's configuration (like a pin in Turbo LED) and then disabling the add-on, the new configuration of the now disabled add-on should be saved when you Save.

### Current Behavior

The configuration of the add-on reverts to it's last state that was saved while the addon was enabled.

Why is this a problem?
Because disabled add-ons lock out Pins in Pin Mapping it is a natural course of behavior to search for the offending add-on, change the config (IE: set Turbo LED's Pin to -1) then disable the add-on, and then save. Then you will scratch your head about why the pin is still locked out in Pin Mapping, and that is because the add-on's config was not saved.

To achieve the expected behavior you must save while the add-on is enabled, then disable the add-on then save again.

### Context

Pico (GP2040-CE_0.7.9_Pico.uf2)
Current: v0.7.9
Waveshare Plus (The Pico Clone) direct soldered to a new custom project.
Windows 11
Firefox

### Steps to Reproduce

1. Enable a disabled add-on
2. Change the configuration.
3. Disable the add-on
4. Save
5. Enable the add-on and see that the config was not saved. Or, witness other evidence like Pin Lockout "Assigned to addon" in Pin Mapping.

**Comment by mikepparks** [comment]
This is not a bug, but an intended design decision. If you need to have your settings saved, save them before disabling the addon.
