### ISSUE TITLE
Switch Mode doesn't work with all games

### ISSUE THREAD

**Issue by darkomen** [OpenStickCommunity/GP2040-CE#110]
Hi, I have tested the switch mode and I detected that the arcade stick doesn't work in all games. But in the Switch menu it does. Is this an expected behavior? It's necessary the game support this control ?

I have tested with the following games:

Sonic Mania: It works
Alex Kidd: It doesn't work
Hades: It doesn't work

**Comment by TheTrainGoes** [comment]
Hey @darkomen ,

By default the Dpad is enabled.  By holding start + select + left or right you can change it to the LS or RS.  

Some games will not work for movement with the Dpad like Hades and must be switched to LS.
