### ISSUE TITLE
Web Config activation button

### ISSUE THREAD

**Issue by beastieboy** [OpenStickCommunity/GP2040-CE#1109]
Sometimes I use this firmware with very simple hardware, like one joystick with 1-3 buttons. That would be good if web config could be easily activated by pressing one of them at boot time. Currently it's hardcoded to S2, but an option in Web Config could be developed to remap it for example to B2.

Here's what I changed to have this feature in Atari 2600 clone one-button joystick:

if (gamepad->pressedS1() && gamepad->pressedS2() && gamepad->pressedUp()) {
					return BootAction::ENTER_USB_MODE;
				} else if (!webConfigLocked && gamepad->pressedB2()) {
					return BootAction::ENTER_WEBCONFIG_MODE;
                } ...

**Comment by TheTrainGoes** [comment]
Hi @beastieboy ,

Web-config being mapped to S2 is a staple of the firmware and not something we are looking to change at this time.

The ability to change it would also lead to more troubles trying to support the firmware on our end as people make changes.

So long as you have access to your BootSel button you can always put the `force webconfig` UF2 (located here https://github.com/OpenStickCommunity/GP2040-CE/releases/download/v0.7.9/force_webconfig.uf2) on which will put the unit into web-config mode when it comes out of BootSel mode.
