### ISSUE TITLE
UART communication for joystick inputs

### ISSUE THREAD

**Issue by Miguel-N** [OpenStickCommunity/GP2040-CE#1124]
### An addon for receiving UART data as the joystick inputs (and probably extra freatures)

I'm working on a project to build a custom game controller that can receive inputs from a second device to program an ai that can play simple games using live video input. I'm thinking of using *two Raspberry Pico Ws* that I already have, one with the gp2040-ce firmware running, and another sending the correct signal to the pico w with the gp2040-ce firmware. For the kind of game i'm trying to test, controlling the joysticks would be preferable, but i'm getting frustrated with the extra hardware required and the rapidly increasing space and connections my project would need. The first approach i though was using Digital to Analog Converters to simulate the analog signal of a real joystick, and reading that through the I2C Analog ADS1219 addon or the adc pins on the pico, given that my first attempt reading a pwm signal only resulted in completly unstable movements. Another option was adding a capacitor and resistor to the pwm output signal from the second pico w (also known as a low pass filter), but i didn't test if it improves performance yet.

### Solution

So, i though that instead of requiring all the extra hardware and components, why not just add the option of reading an uart signal directly from the pico running gp2040-ce? It wouldn't require extra hardware, and the extra pico could be used to add more inputs and functionalities to gp2040-ce, like the extra adc inputs that can then be translated into digital data and sent through the uart connection, and more pins and switches to free some of the pins in the main pico to leave space for usb passthrough authentication, for example. For me, it would simplify adding support for two joysticks, as you would only need another pico and a little bit of code that could easily be programmable on micropython, and the price wouldn't even be that different to buying the I2C Analog ADS1219 and the DAC.

### Do you plan to work on this feature yourself?

I plan on working on it to the extend of my capabilities, but i have no idea of what is the procedure to create extra addons for the gp2040-ce firmware nor how to compile the code correctly so that it runs on my raspberry pico w. I know a little bit of C and C++, but i'm mostly a beginner when it comes to something as complex as this.

Thanks! Any help would be appreciated.

**Comment by TheTrainGoes** [comment]
Hi @Miguel-N ,

This is not something we are interested in implementing at this time.  

SPI or I2C may be better suited to work with our current firmware if you are looking to work on or build a solution yourself.  

If you are just looking to have inputs fed to an RP2040 device running GP2040-CE then I can recommend doing a double stack with shared pins where one RP2040 device is running Python or Arduino code and the other is running GP2040-CE.
