### ISSUE TITLE
When I set several marcos, each time only one will be activated?

### ISSUE THREAD

**Issue by Kawairika777** [OpenStickCommunity/GP2040-CE#1125]
For example I set Pin9 and Pin10 as two different marcos. Each time I connect to the computer. Only one marco will work. It depends on which Pin is first pressed.

**Comment by TheTrainGoes** [comment]
@Kawairika777 we need way more info than this to give you any sort of answer.  

Please fill out the following:

1 - Are you a vendor?
2 - What device are you using?
3 - Where did you buy it? (post link to sales page)
4 - Have you reached out to the vendor with this support question already? (please give a summary of the conversation)
5 - What version and distribution of the firmware are you currently running? (check this via web-config)
6 - What is the problem that you are having?
7 - What trouble shooting steps have you already done?
