### ISSUE TITLE
Compatibility rasbery pico pi 1 and pico pi 2 ? 

### ISSUE THREAD

**Issue by InfernalWolf666** [OpenStickCommunity/GP2040-CE#1145]
I decided to buy the second version of pico pi 2. Are the firmware compatible?

Sorry for the stupid question, I only used arduino uno.

**Comment by InfernalWolf666** [comment]
![Снимок экрана 2024-09-21 042928](https://github.com/user-attachments/assets/64cab625-0830-4803-b440-d20e61dc29ed)

**Comment by mikepparks** [comment]
Not currently supported.  We're investigating the next steps, but they're two different chips.

**Comment by InfernalWolf666** [comment]
> В настоящее время не поддерживается. Мы изучаем следующие шаги, но это два разных чипа.

I'm trying to find information, they seem to be fully compatible. Either an ARM processor can work if the code is written for it, or a RISK processor will work if the code is written for it. They don't work at the same time. But I still haven't figured it out, there's not enough information.

**Comment by mikepparks** [comment]
It is not compatible with the project at the current time.  We will need to make modifications to make sure that everything works as expected. It is planned, but nothing to announce yet.
