### ISSUE TITLE
Mapping of display screen.

### ISSUE THREAD

**Issue by d-411** [OpenStickCommunity/GP2040-CE#1170]
![WechatIMG119](https://github.com/user-attachments/assets/9ad9db1d-82f0-4f47-82fb-a97c3a75a8d7)
### Problem

Dear author, I have modified the mapping of the keys. However, the key mapping on the screen is still the original one. Is there a way to modify the mapping of the screen?

**Comment by d-411** [comment]
My option is i2c0 and the version is 7.10，button layout is stickless.

**Comment by d-411** [comment]
My option is i2c0 and the version is 7.10，button layout is stickless.don't pay attention to the feedback of LED lights. Please focus on the key mapping echo of LED displays.

**Comment by mikepparks** [comment]
Changing the display layout buttons is currently not possible without a custom build. This is planned for a later version.
