### ISSUE TITLE
RGB LEDs + Pico Pi

### ISSUE THREAD

**Issue by InfernalWolf666** [OpenStickCommunity/GP2040-CE#1194]
Tell me how to connect these LEDs to Pico Pi electrically? What pins are needed for this?

![Снимок экрана 2024-10-12 085048](https://github.com/user-attachments/assets/cecf2b06-4ef6-4e66-94cd-f131039114a0)
![Снимок экрана 2024-10-12 084933](https://github.com/user-attachments/assets/908ee08a-492b-4b2a-aef7-a2a389a7f34d)

Thanks

**Comment by InfernalWolf666** [comment]
+ - 3.3V OUT
R - pin ?
G - pin ?
B - pin ?

**Comment by mikepparks** [comment]
Not supported by the firmware sadly.

**Comment by InfernalWolf666** [comment]
> Not supported by the firmware sadly.

Got it. Thank you.
