### ISSUE TITLE
Add Turbo to the RGB LED stack

### ISSUE THREAD

**Issue by TheTrainGoes** [OpenStickCommunity/GP2040-CE#12]
Ability to add the turbo LED to the RGB LED stack + Web UI addition for configuring it.

I am unsure where it should be placed in the RGB LED chain.

Ideally after the Player LEDs, however they do not play will with having things after them.

The configuration for the LED should also include changing the color.

**Comment by arntsonl** [comment]
I'll also take this one on

**Comment by thomasbaart** [comment]
There’s now a bounty of $50 on this request 😌

**Comment by TheTrainGoes** [comment]
This work has been completed
