### ISSUE TITLE
Splash Display Fix + Code Clean-up

### ISSUE THREAD

**Issue by arntsonl** [OpenStickCommunity/GP2040-CE#120]
Splash display is not respecting the default time properly

We need to look at the logic for #define SPLASH_DISPLAY

Additionally, we started having Get* functions in the StorageManager.h which breaks our current coding conventions. We need to remove these and make the StorageManager.h get functions single option only rather than option.<type>

This means we need to get rid of 

int Storage::GetButtonLayout()}
int Storage::GetButtonLayoutRight()
int Storage::GetButtonLayout()
int Storage::GetButtonLayoutRight()
int Storage::GetSplashMode()
int Storage::GetSplashChoice()
int Storage::GetSplashDuration()
int Storage::GetSplashMode()
int Storage::GetSplashChoice()
int Storage::GetSplashDuration()

and start being more strict about PRs that do this.

**Comment by TheTrainGoes** [comment]
This has been addressed.  Thank you @deeebug and @arntsonl
