### ISSUE TITLE
Certain PS3 Games not detecting controller on PS3

### ISSUE THREAD

**Issue by ez2torta** [OpenStickCommunity/GP2040-CE#1201]
> Please read these quoted sections before submitting, and remove them (including this one) when you have provided what
> is asked, in order to make addressing the issue easier for everyone. Thank you!
>
> Be sure to:
> * Check the documentation [HERE](https://gp2040-ce.info/) to answer many questions on firmware capabilities and usage.
> * Make sure that your issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues).
> * Confirm your issue exists on the latest version of the firmware, found
  [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases).

### Expected Behavior
I can use a PS3 with GP2040CE without troubles, in psx games, ps2 classics and some ps3 games.
I mainly play fighting games so i'm testing those.
### Current Behavior
I can play Street Fighter III 3rd strike Online Edition without problems, even Tekken Tag Tournament HD but Marvel vs Capcom 2 and The King of Fighters 13 do not recognise the controller. i have to force PS4 mode to play those games but then i lose Home button which allows me to exit game and other stuff

### Context
Firmware Version: 0.7.10
Board Name: Raspberry Pi Pico
Mode: PS3 Mode

### Steps to Reproduce
Step 1: Get into a PS3
Step 2: Run Marvel vs Capcom 2 or King of Fighters 13
Step 3: Try pressing Start button, it won't get registered.
Step 4: Press Home Button, it works!

This only happens on those two games for now.. The rest of the library works for me

### Screenshots & Files

> Please include any relevant screenshots, photos/recordings, or files here.

**Comment by TheTrainGoes** [comment]
@ez2torta could you try a nuke and reload of v0.7.10 and see if it resolves? 

I can dig out my PS3 and try it.
