### ISSUE TITLE
Macro loaded incompletely after loading from a preset - 0.7.10

### ISSUE THREAD

**Issue by cliu0507** [OpenStickCommunity/GP2040-CE#1206]
### Expected Behavior

The macro settings should be loaded correctly if user saved a preset to *.gp2040

### Current Behavior

Some actions are lost after loading a preset saved before. My observation is that it can only load the first 4 actions for some reasons. 

### Context

This issue doesn't occur in 0.7.8

**Comment by TheTrainGoes** [comment]
Hi @cliu0507,

Was the macro made on a different version of the firmware?

**Comment by cliu0507** [comment]
@TheTrainGoes Hi, yeah I double checked the version of firmware. It is actually  v0.7.9-8-h09 so i edited the title of this issue. Are I supposed to report issue on 0.7.9 still ? I meant the latest is 0.7.10

**Comment by TheTrainGoes** [comment]
Hi @cliu0507 ,

We only take issues on the latest version of the firmware.  If this issue is still in v0.7.10 please make a new issue.
