### ISSUE TITLE
Changes in custom layout for the display don't update in real-time

### ISSUE THREAD

**Issue by Fl0ats** [OpenStickCommunity/GP2040-CE#1225]
I have the same problem as reported before in this closed issue: https://github.com/OpenStickCommunity/GP2040-CE/issues/965#issue-2240479439

### Expected Behavior

>When going into the display configuration and choosing to show a custom button layout, you can move elements around (Start X, Start Y, etc.) and changes in these parameters would immediately be updated on the OLED display.

### Current Behavior

When the product was fresh out of the box and I went to the webconfig I could see those changes in real-time. After updating to 7.10 making changes to the placement of a custom button layout isn't reflected until you save changes ~~and reboot the device~~. Downgrading to 7.9 or 7.8 yields the same results. 

### Context

 * Firmware version: v0.7.10-2-g230983f
 * Board config name: Haute42 COSMOX (GP2040-CE_0.7.10_Haute42COSMOX.uf2)
 * Name of device: Haute42 S16-C
 * Link to where you purchased the device: https://www.aliexpress.com/item/1005007810933539.html
 * Stock firmware out of the box: unfortunately I didn't think about backing-up the fw before updating, I only remember that it had 
 "dirty" in the name. 

### Steps to Reproduce

1. Update from stock fw (including nuking)
>2. In web-config, go into Configuration > Display Configuration
>3. Under Layout Options, change Button Layout Left & Right to the Custom setting
>4. Press B1 on the hardware to see button layout on the OLED
>5. Changing the various custom parameters in web-config, like Star X, isn't reflected immediately on the screen

**Comment by TheTrainGoes** [comment]
Hi @Fl0ats ,

This was a result of a number of changes we made to the back end system that handles the display.  

You are able to see an updated view of the custom layout simply my pressing the `save` button at the bottom of the page in web-config.  So long as you are on the display view it will immediately update.
