### ISSUE TITLE
Combo functions cannot be activated and are not saved.

### ISSUE THREAD

**Issue by Jimizan** [OpenStickCommunity/GP2040-CE#1233]
PiPico zero

fw. GP2040-CE_0.7.10_Pico.uf2
buy Amazon 11/2024

The programmable combo functions cannot be activated and are not saved. The sliders on the side remain grey and are not activated

![photo_2024-12-12_13-43-04](https://github.com/user-attachments/assets/f3cd392b-5729-47fc-b049-778154c95a32)

**Comment by TheTrainGoes** [comment]
Hi @Jimizan ,

This is not a bug.  This is a failure to read the documentation.  

Please reference the information site located at https://gp2040-ce.info/web-configurator/menu-pages/settings to learn more about how to map the FN key so that you ca use FN for hotkey settings.
