### ISSUE TITLE
[FEATURE REQUEST] increase the number of macros that GP2040 supports (current max is 6)

### ISSUE THREAD

**Issue by cliu0507** [OpenStickCommunity/GP2040-CE#1239]
Hi team,

Is it possible to increase the number of macros that the GP2040 CE supports to maybe 8 or 12? Currently it is limited to 6 macros which can maps to 6 buttons.  Is it technically feasible?

Thanks,

**Comment by TheTrainGoes** [comment]
Hi @cliu0507 ,

While technically feasible Macros take up a lot of space so we are not interested in increasing the number beyond the current maximum.  

You are always welcome to fork the repo and make any changes you desire.
