### ISSUE TITLE
Do I need to connect pullup / pulldown resistor to the data pins?

### ISSUE THREAD

**Issue by chikatana** [OpenStickCommunity/GP2040-CE#1242]
I'm new to the GP2040-CE community and plan to make my own controller using Raspberry Pi Pico.

I'm just wondering if I need to connect a pullup / pulldown resistor to each used GPIO pin.

To my knowledge, Raspberry Pi Pico do have it's own integrated pullup / pulldown resistor and will function if enabled in the code. I'm just asking if the pullup / pulldown resistor circuitry is already enabled in the GP2040-CE source code so that I do not need to connect my own.

**Comment by TheTrainGoes** [comment]
Hi @chikatana ,

No resistors needed, just connect a button to a GPIO and ground.  You can chain the grounds as they are all common.
