### ISSUE TITLE
recommended that the general USB HID mode can support SOCD clean off

### ISSUE THREAD

**Issue by oliverCJ** [OpenStickCommunity/GP2040-CE#1248]
I thought that in generic USB HID mode, all buttons could be activated at the same time, but now the D-Pad buttons can't. I think it's the default SOCD Neutral that affects it. Setting SOCD clean off mode also doesn't work. I hope this function can be fixed and supported.

**Comment by TheTrainGoes** [comment]
This was likely overlooked when we implemented USB HID mode as it was copied from PS3 mode.

**Comment by TheTrainGoes** [comment]
@oliverCJ I have fixed this via #1249 

Will go live with the next release.

**Comment by oliverCJ** [comment]
> 我已经通过 #1249 修复了这个问题
> 
> 将在下一个版本中上线。

Thank you so much, it was processed so quickly！
