### ISSUE TITLE
PS4 8 minute timout

### ISSUE THREAD

**Issue by mrdude2478** [OpenStickCommunity/GP2040-CE#1251]
While using on a PS4 console, with a DS4 controller connected via pasthrough or with uploaded files the Raspberry PI Pico times out after 8 minutes and becomes unresponsive until unplugged from the USB socked and then is plugged in again.

All features work as expected on the PS4 during the 8 miuntes the Pico is working for.

I am using the latest GP2040-CE_0.7.10_Pico.uf2 file and did a clean install on a brand new pico.

I was expecting with the uploaded security files that this would work, but it didn't so I cleaned the flash using flash nuke and the reuploaded the GP2040-CE_0.7.10_Pico.uf2 file and set up again. This time I plugged a DS4 controller in and set up to use passthrough but even then after 8 minutes the PI stopped working until unplugged and plugged in again.

**Comment by TheTrainGoes** [comment]
@mrdude2478 the DS4 does not work for passthrough authentication.   

We offer no support about file upload.
