### ISSUE TITLE
Bounty - SOCD slider switch

### ISSUE THREAD

**Issue by TheTrainGoes** [OpenStickCommunity/GP2040-CE#133]
Like the currently implemented LS/RS/DP slider we are hosting a bounty to have an SOCD slider switch added in to the addon section.

Conditions for completion of the bounty:
- Added into the code in the same way our other addons are done
- Tested and working
- Does not impact other addons
- Added into web-config

The default state of this addon should be off.  It should use two GPIO pins.  The default state should be SOCD neutral as it is now.

**Comment by arntsonl** [comment]
It's in release! Closing this, nice work @deeebug !
