### ISSUE TITLE
Link to Pico pinout broken (in gp2040-ce.info)

### ISSUE THREAD

**Issue by aserrallerios** [OpenStickCommunity/GP2040-CE#139]
This link is broken:

https://gp2040-ce.info/#/configs/Pico/assets/PinMapping.png

**Comment by TheTrainGoes** [comment]
Hi @aserrallerios  - Thank you for the report.  I am not quite sure why the link is broken but we will get it fixed up.

**Comment by TheTrainGoes** [comment]
This has been resolved in a PR
