### ISSUE TITLE
Dropped Inputs On Update 0.6.3

### ISSUE THREAD

**Issue by troytroy22** [OpenStickCommunity/GP2040-CE#141]
I'm noticing multiple different boards with the new update 0.6.3 is experiencing dropped inputs. Tested On TheTrain V4 , ArcadePCBs Type C Board and My Embedded Mini All-button Controller. Going back to 0.6.2 fixes this on each board. Each board was flash nuked before update. Quickly Pressing a button will show the issue.

**Comment by fangxiang-gan** [comment]
Yes, I have the same problem 0.6.3

**Comment by TheTrainGoes** [comment]
Hi @troytroy22 and @fangxiang-gan ,

We have rolled back v0.6.3 due to this issue as well as a few other issues.  

We will re-release when we are able to resolve those issues.  

Thank you for the report.
