### ISSUE TITLE
Turbo Shot Count Does Not Increase or Decrease on 0.6.3

### ISSUE THREAD

**Issue by troytroy22** [OpenStickCommunity/GP2040-CE#142]
Turbo shot count reverts back to 5 or 8 after change of setting. Changing the turbo shot count with controller shortcut "Turbo+Up/Down" does not save and reverts back to 5 or 8. Saving Turbo shot rate in Webconfig results in same issue. Tested on TheTrain v4, arcadepcbs type c, and Slab mini embedded all-button mini controller. Going back to 0.6.2 fixes this issues and each board was flashed nuked before update.

**Comment by TheTrainGoes** [comment]
Hi @troytroy22 ,

There were some issues with v0.6.3 so we have rolled back to v0.6.2.  We are working to address the issues and will re-release in time.  Once re-released please test again and submit a new issue if you are still able to replicate.  

Thank you,
