### ISSUE TITLE
Create menu-based configuration for systems with OLED screens

### ISSUE THREAD

**Issue by FeralAI** [OpenStickCommunity/GP2040-CE#144]
Per @TheTrainGoes on Discord:

> Make config via OLED a thing and we can update the board 🙂

But on a serious note, it would be nice to be able to at least select the runtime options like input type, SOCD method, LS/RS emulation, etc. via menu selections for OLED controllers. Avoids having to remember a bunch of button combinations to toggle options.

**Comment by Fortinbra** [comment]
As a note: There should never be a hard dependency on the OLED for any settings. We must support builds that do not have an OLED.

**Comment by FeralAI** [comment]
Of course @Fortinbra, this would just be additional functionality for the existing OLED/screen support.

**Comment by TheTrainGoes** [comment]
We are going to close this for now and revisit or remake at a later time.
