### ISSUE TITLE
Turbo Shot Count always in 8 times  v0.6.3

### ISSUE THREAD

**Issue by xboxgod** [OpenStickCommunity/GP2040-CE#146]
Raspberry PICO, already clearn flash, and update to 0.6.3
but setting any Turbo Shot Count number, after reconnect usb, It will auto recover to 8

is this a problem?

**Comment by TheTrainGoes** [comment]
Hi @xboxgod ,

There are some known issues with v0.6.3 so we have rolled back to v0.6.2.  I would recommend downgrading until we release again and then submit a new issue if you are able to replicate it on the re-release of v0.6.3
