### ISSUE TITLE
Web config - Make all usage options available on Settings page

### ISSUE THREAD

**Issue by FeralAI** [OpenStickCommunity/GP2040-CE#148]
The current Settings page is a little bare and would be a great place to centralize all the runtime options that are adjustable for addons. Options like:

* Turbo addon - Turbo Shot Count & Shmup mode toggle
* Input Reverse - All directional options
* Dual Direction Input - Dual D-Pad Mode and Combination Mode
* Buzzer Speaker - Buzzer volume
* Extra Button - Extra Button value
* Player Number

The current addon configuration can keep these values, it would just be nice to expose them all at once on the Settings page.

**Comment by TheTrainGoes** [comment]
We are going to close this for now but will revisit when we do some web-config changes
