### ISSUE TITLE
SOCD cleaning slider should be configurable

### ISSUE THREAD

**Issue by henrebotha** [OpenStickCommunity/GP2040-CE#157]
Using a 3-way slider works if you have exactly 3 SOCD algorithms, but the moment we add more (or the ability to disable SOCD (#156)), it fails. Probably most users won't have an arbitrary number of pins available to dedicate to a huge slider that covers all bases (nor would they want to be able to switch between all algorithms), so ideally the user should be able to specify a list of SOCD algorithms to use. Board should read this list from config in order to map slider positions to algorithms.

**Comment by TheTrainGoes** [comment]
@deeebug this is good feedback and would allow for easier implementation of the first input + no SOCD modes.

**Comment by deeebug** [comment]
Yes, already on that. First part of it was making hotkeys configurable.

**Comment by deeebug** [comment]
An implementation for this has been added, please check that out and close this issue if things are good enough.
