### ISSUE TITLE
0.6.3 I found the problem

### ISSUE THREAD

**Issue by fangxiang-gan** [OpenStickCommunity/GP2040-CE#163]
The firmware I am using is GP2040-CE_ 0.6.3_ PicoFightingBoard.uf2, I found the following problem: I assigned pin16&pin17 to the SOCD Selection Slider and pin18&pin19 to the Joystick Selection Slider. The joystick will experience a random lag. Especially for pin 16, as long as it is used, exceptions will occur, such as assigning it to Dual Directional Input. Are these four sets of pins unusable? I see in the instructions that these four sets of pins are used for player LEDs, but I don't think they are very useful. It would be a good choice to assign them to slider switches.
Thanks.

**Comment by arntsonl** [comment]
We will try to replicate on our end, can you send a picture of your setup?

Additionally, can you let us know what kind of sliders you are using for these selections?

Pin 16,17,18, and 19 should be fine for these options.

**Comment by TheTrainGoes** [comment]
Hi @fangxiang-gan ,

The issue here is likely that on the Pico Fighting Board there are resistors on pins 16,17,18 and 19 for the intended Player LEDs.  

If possible can you retry this mapping them to some of the normal pins?

**Comment by fangxiang-gan** [comment]
![1](https://user-images.githubusercontent.com/128204669/233410507-5a5a620e-52be-46da-9e13-e7a3f48c3f86.png)
![2](https://user-images.githubusercontent.com/128204669/233410513-0937e5eb-171a-4a28-8185-19572f700015.png)
![3](https://user-images.githubusercontent.com/128204669/233410515-f7297352-5e8a-45b1-8d95-67122a6a5499.png)

**Comment by fangxiang-gan** [comment]
The frame I am using is Razer Panthera
![4](https://user-images.githubusercontent.com/128204669/233415145-1e4618d6-3cbd-4a4f-ae97-454b4a0442f9.png)

**Comment by fangxiang-gan** [comment]
If set as shown in the following picture, the direction will be 100% chaotic. My system is Windows 10 64bit. 
Thank you.
![6](https://user-images.githubusercontent.com/128204669/233420800-292ec09d-78b5-4124-a8b9-3f2da6735623.png)

**Comment by TheTrainGoes** [comment]
Hi @fangxiang-gan,

Reposting my previous comment:

The issue here is likely that on the Pico Fighting Board there are resistors on pins 16,17,18 and 19 for the intended Player LEDs.

If possible can you retry this mapping them to some of the normal pins?

---

Can you please also post a pic of the controller board you are using?  

Additionally, there may be issues with how that aux board does its slide switch.  Many factors to consider.

**Comment by fangxiang-gan** [comment]
Hi@TheTrainGoes，

Hello, here is the controller chip I am using.
![00](https://user-images.githubusercontent.com/128204669/233519400-8eceaccc-d6eb-4a08-b575-2cf443b6d313.jpg)
![0](https://user-images.githubusercontent.com/128204669/233519408-1781c80c-3694-4717-b651-3bbaf1ee5953.jpg)

I used the following settings and did not find any problem with directional drift, which is normal.
![8](https://user-images.githubusercontent.com/128204669/233519469-aeea9473-d4fe-48b9-acb1-ad844a5b53bd.png)
![9](https://user-images.githubusercontent.com/128204669/233519470-2c510a0a-7a44-4393-89bd-fc821e3aaeb8.png)

thank you.

**Comment by fangxiang-gan** [comment]
There will still be problems, as shown above, with double clicking in all directions. -_-

**Comment by TheTrainGoes** [comment]
Hi @fangxiang-gan - These 26/27/28 are ADC pins.  Can you please try some of the other pins and see if the behaviour continues?

**Comment by fangxiang-gan** [comment]
Hi@TheTrainGoes，
The remaining pins are not allowed to be set to a value of -1. Only these pins 15, 16, 17, 18, 19, 25, 26, 27, and 28 can be used and have all been used. thank you.

**Comment by TheTrainGoes** [comment]
Hi @fangxiang-gan ,

Checking in on this - Are you able to replicate this with the new v0.7.1 pre-release?

**Comment by fangxiang-gan** [comment]
> @TheTrainGoes 
Yes, 0.7.1. As long as LS and RS are open for 16~19pin, the direction will appear random sticky.
![111111111](https://github.com/OpenStickCommunity/GP2040-CE/assets/128204669/4007c4a7-7e0f-4a24-9042-c3c8d227b521)

**Comment by TheTrainGoes** [comment]
One last question on this, 

Are you able to replicate this when the unit is not connected to your Razer Panthera?

**Comment by fangxiang-gan** [comment]
Yes, as long as LS and RS are on and specified as 15~19, 26, 27, 28pin, the direction will appear random sticky, and turn off completely normal. It has nothing to do with my Razer slider switch, as I tested it directly with the pico chip. 
thank you

**Comment by TheTrainGoes** [comment]
Hi @fangxiang-gan - Are you able to replicate this on [v0.7.1-RC2](https://github.com/OpenStickCommunity/GP2040-CE/releases/tag/v0.7.1-RC2)?

**Comment by fangxiang-gan** [comment]
Hi@TheTrainGoes 
My test results for 0.7.1-RC2 are as follows: if LS and RS are set to 16pin, 17pin, left analog, or gamepad. The direction is almost collapsed and cannot be used. See the video below. If LS and RS are set to 18pin and 19pin, the direction is close to normal, with an XY rotation flashing every 3 minutes.
Thank you for your continuous follow-up.
https://github.com/OpenStickCommunity/GP2040-CE/assets/128204669/04221685-fc9e-4066-9e1e-d3cdc74c5fe9

**Comment by TheTrainGoes** [comment]
Hi @fangxiang-gan ,

Is this issue still present in v0.7.2?
