### ISSUE TITLE
SOCD slider introduces significant input delay using PicoAnn

### ISSUE THREAD

**Issue by kdliu86** [OpenStickCommunity/GP2040-CE#178]
I am using @TheTrainGoes's Advanced Fighting Board Rev 3 running GP2040-CE_0.6.3_PicoAnn.uf2.

I installed my on/off/on switch, with the SOCD pins set to pin 16 and 17 (player leds on the PicoAnn pin out).

I am only getting up priority and all neutral, last input wins does not work.  Additionally I am getting significant input delay (maybe dropped inputs?).

Nuking and going back to 0.6.2 removes the delay and it returns back to normal.

**Comment by TheTrainGoes** [comment]
@kdliu86 have you tested this on v0.7.1?  This should be resolved now.

**Comment by TheTrainGoes** [comment]
Closing due to lack of response
