### ISSUE TITLE
Analog stick input

### ISSUE THREAD

**Issue by steryo** [OpenStickCommunity/GP2040-CE#188]
Input is broken on 0.6.3 which works perfect on 0.6.1, I think the stick issues may be related to this version. Using GP26(as x) and GP27(as y), only the axis on 26 works and nothing happens on 27 input in my case.

**Comment by TheTrainGoes** [comment]
Hi @steryo ,

Have you checked this out on the new pre-releases?

**Comment by TheTrainGoes** [comment]
Closing due to no reply
