### ISSUE TITLE
Properties being dropped when saving addon settings

### ISSUE THREAD

**Issue by mikepparks** [OpenStickCommunity/GP2040-CE#196]
After some testing, it seems that the amount of new properties for addons has caused the JSON doc to expand beyond the 2048 limit from LWIP_HTTPD_POST_MAX_PAYLOAD_LEN in webconfig.cpp. This may impact some of the newly added addons, and was only noticed on hardware since the local web server instance does not have this limitation.

**Comment by mikepparks** [comment]
![image](https://user-images.githubusercontent.com/1214033/235419150-cb69340e-5942-477d-9552-1564f58d1def.png)
This is a compare against the setAddonsOptions API route. The left is the POST payload. The right is the same doc being returned.

**Comment by TheTrainGoes** [comment]
Thanks for the info @mikepparks - We will look into this.

**Comment by arntsonl** [comment]
Should be fixed! pull latest and try it out

**Comment by TheTrainGoes** [comment]
This has been addressed in [v0.7.1-RC2](https://github.com/OpenStickCommunity/GP2040-CE/releases/tag/v0.7.1-RC2)
