### ISSUE TITLE
(Feature request) Allow inverting button activation

### ISSUE THREAD

**Issue by Aigis** [OpenStickCommunity/GP2040-CE#213]
This is a bit of an edge case, but would it be possible to set specific pins to register high instead of low? The use case that I have is the Xbox 360 Hori Fighting Edges start/select touchpad, which appears to activate inverse from the rest of the buttons (It holds the input and then lets go upon pressing when I hook it up to a Brook UFB). Being able to set some pins to follow this behavior would enable me to upgrade this case, retain the touchpad without adding anything extra into the board. Sadly the original pcb was damaged before I bought it so I can't just piggyback off of it

**Comment by TheTrainGoes** [comment]
Hey @Aigis,

Believe it or not I actually designed a replacement PCB for these that uses the Pico haha.  

If you are on Discord toss me a message and I can send you the plans for it.
