### ISSUE TITLE
Create SEO/webmaster to get gp2040-ce.info into webcrawlers

### ISSUE THREAD

**Issue by arntsonl** [OpenStickCommunity/GP2040-CE#216]
We should have some kind of SEO/webmaster account for gp2040-ce.info to get into webcrawlers.

From FeralAI:

One other note, we may want to submit gp2040-ce.info to search engines manually for crawling/indexing. I haven't done this since the project should have control of that and I don't believe there are any SEO/webmaster accounts set up to handle this.

**Comment by TheTrainGoes** [comment]
We are going to close this for now as project growth and discoverability has been good.  In the future we may look at promoting more via search results.
