### ISSUE TITLE
I know this is supposed to work with brook wingman adapters but does anyone know if it works with mayflash adapters? Thanks!

### ISSUE THREAD

**Issue by jojo22904** [OpenStickCommunity/GP2040-CE#22]

**Comment by arntsonl** [comment]
It works great with the MAYFLASH Magic NS Wireless adapter. Is there a specific Mayflash adapter you're curious about?

**Comment by okkdev** [comment]
Yes. I use it on PS4/PS5 with Mayflash Magic Pro 2 and Magic Ultimate.

**Comment by jojo22904** [comment]
@okkdev 
What is the difference between those two adapters and which one do you recommend?

**Comment by okkdev** [comment]
Ultimate is the successor of the Pro 2. Get the Ultimate. :)

**Comment by jojo22904** [comment]
@okkdev 
Okay thank you so much!

**Comment by TheTrainGoes** [comment]
Closing issue, glad to hear it works.
