### ISSUE TITLE
Bug: Documentation's link to the configs folder is broken

### ISSUE THREAD

**Issue by micfok** [OpenStickCommunity/GP2040-CE#23]
From: https://gp2040-ce.info/#/?id=installation

Clicking on the link for the config folder leads to a 404 (https://gp2040-ce.info/#/configs)

![image](https://user-images.githubusercontent.com/2171011/208979077-6800b74c-55f4-4240-8c1f-09c35f44ed10.png)

![image](https://user-images.githubusercontent.com/2171011/208979138-6fbee1e5-ea19-44ab-ad0d-21324ae5fcf5.png)

**Comment by TheTrainGoes** [comment]
Thanks for the heads up @micfok , 

Let me get this fixed up

**Comment by TheTrainGoes** [comment]
Closing this out.  

@micfok this was a legacy thing where there used to be configs available that were not pre-compiled in the original GP2040 repo.  

Currently we have releases available for all of the supported configurations.  

If you are looking for something specific that is not on the list please let me know or send me a message on Discord an I can try to help out.

**Comment by micfok** [comment]
Ah, you already helped me out last night when I was trying to find the default pin mapping for the Pi Pico. I had assumed that folder was where I was originally supposed to find that mapping because I wasn't able to find it on the documentation page. Figured I would raise that bug or highlight that the documentation doesn't currently direct newcomers what they should wire their first button to (in order to hit the `S2` to open the web configurator.)

**Comment by TheTrainGoes** [comment]
Got it!  Glad we got it sorted.  I made a sec section of the documentation with all the shortcuts in one place to help.
