### ISSUE TITLE
Map analog directions in addition to digital ones

### ISSUE THREAD

**Issue by KurtMage** [OpenStickCommunity/GP2040-CE#237]
[The cross-up](https://www.hitboxarcade.com/products/cross-up) is a stick that has both the stick itself, traditional 8 button layout, and an additional 4 button that are mapped to the cardinal directions of the analog stick. It feels like this should be possible to do here as well.

If anyone can point me in a good direction to start looking at this, I may be able to implement it at least for my own stick, but it would be cool if the pin mapping in the web config also had spots for `Up (analog)`, `Down (analog)`, etc.

(also @FeralAI we talked on discord a couple years ago, hello again!)

**Comment by InfraredAces** [comment]
This should have been addressed with the [Dual Directional Input Add On](https://gp2040-ce.info/#/web-configurator?id=dual-directional-input). How to implement this is in the Webconfig documentation under Dual Directional Input. 

Please read this first and then come back if you run into any issues.
