### ISSUE TITLE
Dual Directional input not working as intended

### ISSUE THREAD

**Issue by KurtMage** [OpenStickCommunity/GP2040-CE#240]
I want to have one set of buttons correspond to the dpad and another set be the left analog stick, similar to the GENERIC MULTI DIRECTIONAL ARCADE UNIT. Based on documentation, it looks like [dual directional input](https://gp2040-ce.info/#/web-configurator?id=dual-directional-input) should get me what I want.

In `Settings` I set the regular buttons to Dpad and in the `Dual Directional Input add-on`, I set it to left analog stick. Behavior was different in different modes, but none were what is described in documentation. What I observed was:

`Mixed`: Both sets of buttons give Dpad output.

`Gamepad`: the dual directional input add-on buttons give left analog stick output (yay), but the regular buttons give both Dpad and left analog stick output simultaneously.

`Dual directional`: I actually do not remember what I saw here, but it was definitely not what I wanted.

`None`: The dual directional input add-on buttons are disabled entirely. 

I'm not sure if this is relevant, but I am only mapping left/right. I have not tested anything with up/down. In the meantime, `Mixed` gives me effectively the behavior I want, it's just technically illegal to be mapping the Dpad to two sets of buttons.

**Comment by bsstephan** [comment]
Hello, I recently fixed DDI mode `None` in PR #220 --- please take a look at my notes there to see that it accomplishes what you want, but your use case sounds the same as mine. It is in the mainline code and will be in the next release, AFAIK.

**Comment by KurtMage** [comment]
That's great to hear! I'll keep an eye out for the new release. Thanks!

**Comment by TheTrainGoes** [comment]
Sorry @KurtMage - had to edit your original post to change a name in there.

**Comment by bsstephan** [comment]
@KurtMage - want to try v0.7.1 now?

**Comment by TheTrainGoes** [comment]
Closing due to lack of reply - should be fixed in PR#220

**Comment by KurtMage** [comment]
Finally got around to testing. Looks good to me! Thanks!

**Comment by TheTrainGoes** [comment]
Closing - Issues resolved in v0.7.1
