### ISSUE TITLE
Issue with up/down on Ps3, and asking for compatibility on Ps2

### ISSUE THREAD

**Issue by Pabletex91** [OpenStickCommunity/GP2040-CE#242]
I just replaced my old "zero lag" board with a original pi pico, works waaay better on my pc, but in my ps3 (I realized this on the xmb, but no in games) when I move up or down, sometimes it gets stuck until I move again.

I also want to know if you could add Ps2 compatibility through OPL and Pademu, I plugged in Ps3/Ps4 mode and no response, my Ps2 would be very happy :)

Thanks in advance

**Comment by henrebotha** [comment]
Best to split up issues. It helps developers keep better track of progress. I suggest you edit this issue & title to just cover the up/down bug, and create a new issue for the PS2 compat.

**Comment by wrennnnnn** [comment]
the first issue happens on original hardware (dualshock 3 and original ps3). not sure why it happens, though.

**Comment by TheTrainGoes** [comment]
@Pabletex91 based on the comment from @wrennnnnn the first issue is normal behaviour.  

For the 2nd comment about PS2 support please feel free to file a new issue and possibly sponsor a bounty around it.
