### ISSUE TITLE
No way to tell if PS4 key upload failed or succeeded

### ISSUE THREAD

**Issue by aserrallerios** [OpenStickCommunity/GP2040-CE#245]
After enabling the add-on, selecting the keys and Verify/Save them, I get a "success" message, but after loading the Web Configurator again I see the PS4 add-on disabled.

Either the process has failed, or the add-on should be enabled with a hint that the controller is ready to use in PS4 mode (i.e. it has valid keys).

**Comment by TheTrainGoes** [comment]
Hi @aserrallerios,

Are you doing this on v0.7.0?  There was an issue with the saving of web-config options that may be leading to this.

**Comment by aserrallerios** [comment]
Hey @TheTrainGoes, it was the 0.7.1 downloaded 3 days ago.

**Comment by aserrallerios** [comment]
Duplicate.
