### ISSUE TITLE
read accelerometer/gyro and output value to joystick axis.

### ISSUE THREAD

**Issue by MechatronikMonkey** [OpenStickCommunity/GP2040-CE#258]
To detect nudging, position, rotation etc.
Some people use this firmware for Virtual Pinball Tables where physical inputs have great impact on the game.

Most ACC or gyro Chips out there for Arduino come with pretty good drivers in C/C++. Should be easy to implement.

I am Embedded C/C++ Dev.... if someone gives me a little help on the software structure and architecture, I can code this function.

**Comment by henrebotha** [comment]
This would be an add-on, probably. Here are some examples of existing add-ons that use analogue output.
- https://github.com/OpenStickCommunity/GP2040-CE/blob/main/src/addons/analog.cpp
- https://github.com/OpenStickCommunity/GP2040-CE/blob/main/src/addons/i2canalog1219.cpp
- https://github.com/OpenStickCommunity/GP2040-CE/blob/main/src/addons/wiiext.cpp

**Comment by TheTrainGoes** [comment]
We are going to close this request due to lack of interaction and revisit when we have the expansion board finished.
