### ISSUE TITLE
Y-Invert does not apply to Extra Button (Up)

### ISSUE THREAD

**Issue by InfraredAces** [OpenStickCommunity/GP2040-CE#259]
# Prerequisites

- [ X ] I am running the latest version
- [ X ] I checked the documentation and found no answer
- [ X ] I checked to make sure that this issue has not already been filed
- [ X ] I'm reporting the issue to the correct repository

## Expected Behavior

When inverting Y-axis, up input bound using Extra Button Add On inputs down, matching the behavior of the original up input.

## Current Behavior

When inverting Y-axis, up input bound using Extra Button Add On inputs up even when the original up input is properly inverted.

## Steps to Reproduce

1. Enable the Extra Button Add On
2. Assign the proper pin to Extra Button Pin
3. Invert the Y-axis input of the D-pad by pressing START + HOME + RIGHT
4. Press the original up input (correctly inverts)
5. Press the extra up input (does not invert)

## Context

* Firmware Version: 0.7.1
* Operating System: Arch Linux
* Browser: Chrome

**Comment by TheTrainGoes** [comment]
This has been resolved - closing
