### ISSUE TITLE
Bounty - Aux button lockout add-on. 

### ISSUE THREAD

**Issue by fatihG** [OpenStickCommunity/GP2040-CE#268]
While I realize a physical switch might work better, if possible I would like to ask for an add on that when pressed effectively renders the menu buttons as non functional, until the 'lock' button gets pressed again.

**Comment by TheTrainGoes** [comment]
Hi @fatihG ,

We have talked about this request a few times in the past.  At the time we were more focused on core features but I think we can take another spin at this.  

In a basic implementation this will need either a latching switch or a slide switch that has two positions.  

I will host a bounty for this.

**Comment by TheTrainGoes** [comment]
Bounty:

Aux button lockout add-on will allow a slide or latching switch connected to a GPIO pin to dictate other buttons which will no longer respond to presses.  

As an example, when the Aux button lockout add-on is enabled and the slide switch is in the on position, S1, S2, A1, A2 no longer respond to presses.  

The web-config section for this add-on should allow you to set the following:
- Aux button lockout add-on pin
- Any number of buttons that can be affected by this add-on

I am open for discussion on if this should prevent someone from being able to enter web-config should they have S2 locked out.

**Comment by TheTrainGoes** [comment]
This work has been completed and the issue will be closed.
