### ISSUE TITLE
Bounty - Forced setup mode

### ISSUE THREAD

**Issue by TheTrainGoes** [OpenStickCommunity/GP2040-CE#272]
Forced setup mode is intended for operators and individuals who may be putting these boards into dedicated setups and do not want the ability to change options once installed.

This bounty would be either an add-on or an addition to the settings page.

It will allow you to:
- Lock a mode (holding P1, P2, K1, K2 on boot no longer changes modes from the set mode)
- Remove any or all hotkey combos (this is already in, not sure if we want to wrap it all together)

**Comment by bsstephan** [comment]
It might be worth a quick discussion at some point if the "Function" key (#239) ought to solve this problem by essentially claiming mode selection, web configurator at boot, etc. are hotkeys, and then the setup mode requested here would be enabled by defining the pin for Fn (which is unset by default, but could be set to a pin only populated via a jumper or on a button/switch not accessible by users). Function (currently a core button) could change --- it's in a WIP waiting for at least protobuf to merge, right now, anyway --- so we have time to redesign it before it goes in.

And to be fair, it's equally possible that "Function" serves as a runtime alternate function key (modifiers e.g. tilts, as BRP said on Discord), but what I was envisioning was more of a "disabling hot keys" thing than a "changing behavior" thing (though both are valuable). If we want "Function" to be runtime then I may un/redo #239 and take this on separately.

Or maybe "forced setup mode" is different than "disabling hot keys" in which case we have three buttons?? I don't know. Anyone with opinions, ping me. =)

**Comment by TheTrainGoes** [comment]
This work has been completed.
