### ISSUE TITLE
Issue: Extra Button not available in LED chain

### ISSUE THREAD

**Issue by InfraredAces** [OpenStickCommunity/GP2040-CE#278]
### Prerequisites

Please check the following before posting an issue / bug report.

- [x] I am running the latest version of the firmware found [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases)
- [x] I have checked the documentation [HERE](https://gp2040-ce.info/#/) and found no answer
- [x] I checked to make sure that this issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues)
- [x] I am reporting the issue to the correct repository

### Context

Please provide all relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.  

* Firmware Version: 0.7.1
* Name of device: Custom
* Link to where you purchased the device: Custom
* Is this a custom build?: Yes
* Operating System: Arch Linux
* Browser: Chrome

### Expected Behavior

When the Extra Button Add On is enabled, the Extra Button shows in the RGB LED Button Order menu and can be added to the RGB LED chain.

The option to configure the Extra Button into the RGB LED chain within BoardConfig.h to remove the need for accessing the web configurator.

### Current Behavior

When the Extra Button Add On is enabled, the Extra Button does not show in the RGB LED Button Order menu and cannot be added to the RGB LED chain.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Enable the Extra Button Add On
2. Assign the Extra button pin and input
3. Navigate to the RGB LED Configuration in the Web Configurator

### Screenshots & Files

![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/44279698/b7952ff0-d986-4e26-9f2e-062b2e8a21ff)
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/44279698/a9fc1370-91e6-4625-a230-649300c5a7fe)

**Comment by TheTrainGoes** [comment]
Hi @InfraredAces ,

This is a known issue as both instances of the extra button are the same to the RP2040.

This, I believe, will also be addressed when we revamp the LED stuff.
