### ISSUE TITLE
The web configurator is English only

### ISSUE THREAD

**Issue by SavageCore** [OpenStickCommunity/GP2040-CE#285]
### Have you checked the GP2040-CE documentation [HERE](https://gp2040-ce.info/#/) to confirm this feature doesn't already exist?

Yes

### Which problem is this feature request solving?

Non-English speakers are not able to use the web config.

### Describe the solution you would like to see

Under settings, there should be a dropdown to choose supported languages. We should also auto-select the users' language with `i18next-browser-languagedetector`.

### Describe alternatives you've considered

Pretend English is number 1 and no one else exists. 🇬🇧 🇬🇧

### Can you submit a pull request?

Yes

### Are you planning on working on this feature yourself?

Yes. I've started here: https://github.com/SavageCore/GP2040-CE/tree/feature/i18n

I can extract all of the English strings and prepare the app for translators but then we'll need community members to do the rest! Or DeepL 🤷

**Comment by FeralAI** [comment]
@SavageCore I took a look at the changes on your branch and the implementation looks nice and clean! We're currently discussing methods of maintaining the translation files once the feature is present. Feel free to PR this when you feel it's ready.
