### ISSUE TITLE
Audio Support

### ISSUE THREAD

**Issue by Fortinbra** [OpenStickCommunity/GP2040-CE#290]
Placeholder for adding audio support, for feature parity with first party controllers.

- [ ]  Support for I²S for most common DAC chips
- [ ]  Support for an audio DAC chipset, such as the TI PCM51xx series.

**Comment by Fortinbra** [comment]
- [ ] Support for I²S for most common DAC chips
- [ ] Support for an audio DAC chipset, such as the TI PCM51xx series.

**Comment by TheTrainGoes** [comment]
We are going to close this until the expansion board is completed.
