### ISSUE TITLE
External Input Support

### ISSUE THREAD

**Issue by Fortinbra** [OpenStickCommunity/GP2040-CE#291]
Placeholder for implementing external inputs, such as the Wii Nunchuck, or SNES controller.

This can become a very long list, so for brevity, we're only asking for baseline support, with additional devices and features added later.

- [ ] External inputs from existing add-on devices, such as Wii classic controller, or Guitar.
- [ ] External inputs from classic console controllers, such as the SNES.

**Comment by arntsonl** [comment]
One of the issues we have right now is that external devices do not trigger "gamepad state" changes before we perform boot options.

This means that SNES and Wii controllers cannot boot the device into web-config mode, or an alternative status.

**Comment by TheTrainGoes** [comment]
We are going to roll this into a more curated retro console support series of issues.
