### ISSUE TITLE
Haptic Feedback Support

### ISSUE THREAD

**Issue by Fortinbra** [OpenStickCommunity/GP2040-CE#292]
Placeholder for adding support for haptic feedback via ERM or LRA devices.

- [ ]  I²C support for haptic engine chipsets, such as the TI DRV2605 chips

**Comment by Fortinbra** [comment]
- [ ] I²C support for haptic engine chipsets, such as the TI DRV2605 chips

**Comment by TheTrainGoes** [comment]
We are going to close this until the expansion board is completed.
