### ISSUE TITLE
Xinput mode not detected in uBlue Fedora Kinoite

### ISSUE THREAD

**Issue by outphase** [OpenStickCommunity/GP2040-CE#302]
* Firmware Version: 0.7.0
* Name of device: GP2040-CE
* Link to where you purchased the device: @TheTrainGoes 
* Is this a custom build?: 
* Operating System: uBlue Fedora Kinoite
* Browser: Firefox

### Expected Behavior

Detecting Xinput in Steam

### Current Behavior

Not being detected or recognized

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Boot holding K2
2. Open Steam or gamepad-tester.com

### Explanation

I recently got a GP2040 board running 0.7.0 and have installed it into my PS3 MadCatz TE1. The functionality of the board is generally good. I have currently tried using Switch, Xinput and Dinput modes in both Linux () and Windows.

Web-config works in both OSes. Windows is able to see Switch and Xinput modes without an issue, but Linux is unable to see Xinput mode at all, and Dinput is mapped randomly (which is an ignorable issue because I don't intend on using Dinput). Linux is able to work with Switch mode.

Linux already has udev rules from https://gitlab.com/jntesteves/game-devices-udev/-/blob/main/71-microsoft-controllers.rules and the `steam-devices` package layered in with `rpm-ostree`. I have run `lsusb` and saw that it is detected at `045e:028e` but with a slightly different name than in the udev rule. However, Steam and gamepad-tester.com are not detecting the board in Xinput mode.

Does anyone have any insight as to what I can do on my end to ensure that Xinput mode can work in Linux?

**Comment by bsstephan** [comment]
For comparison's sake here's what you should get in Linux if you run `dmesg`:
```
[1825581.377296] usb 5-1.3: new full-speed USB device number 10 using xhci_hcd
[1825581.408188] usb 5-1.3: New USB device found, idVendor=045e, idProduct=028e, bcdDevice= 1.14
[1825581.408193] usb 5-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[1825581.408195] usb 5-1.3: Product: XInput STANDARD GAMEPAD
[1825581.408197] usb 5-1.3: Manufacturer: Microsoft
[1825581.408198] usb 5-1.3: SerialNumber: 1.0
[1825581.476279] input: Microsoft X-Box 360 pad as /devices/pci0000:00/0000:00:08.1/0000:0d:00.3/usb5/5-1/5-1.3/5-1.3:1.0/input/input128
```
and in KDE's Game Controller tool:
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/45223/ede88b97-f494-4745-afc6-bbb1a4fd86af)

IIRC you need `CONFIG_JOYSTICK_XPAD` in your kernel (or as a module) for it to get recognized by the input layer and appear as a joystick. I don't know how to do that on your distro though.

**Comment by bsstephan** [comment]
Also, what is "random" about DInput mode? You may have weird wiring going on, but also note that it orders buttons 1-4 differently than on XInput.

**Comment by outphase** [comment]
Based on these comments and additional input on Discord, I rebased with a version of Kinoite that includes `xone`. The problem appears to be solved with the `xone` package.
