### ISSUE TITLE
Hotkeys don't change when Touchpad and Share are switched in PS4 Mode

### ISSUE THREAD

**Issue by jazonandes** [OpenStickCommunity/GP2040-CE#314]
### Prerequisites

Please check the following before posting an issue / bug report.

- [x] I am running the latest version of the firmware found [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases)
- [x] I have checked the documentation [HERE](https://gp2040-ce.info/#/) and found no answer
- [x] I checked to make sure that this issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues)
- [x] I am reporting the issue to the correct repository

### Context

Please provide all relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.  

* Firmware Version: 0.7.2-RC2
* Name of device: Custom
* Link to where you purchased the device: Custom
* Is this a custom build?: Yes
* Operating System: Windows 10
* Browser: Firefox

### Expected Behavior

When Touchpad and Share are switched, the Web Configurator states that A2+S2 / Touchpad+Options should be held to access the first set of hotkeys.

### Current Behavior

When Touchpad and Share are switched, S1+S2 / Share+Options must still be held in order to access the hotkeys.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Change input mode to PS4.
2. Switch Touchpad and Share in the Web Configurator.
3. Attempt to access hotkeys by holding A2+S2 / Touchpad+Options.

### Screenshots & Files

![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/58129136/7e364dfc-1c43-4caf-9bee-69d95a28a5cb)
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/58129136/ece6e0ac-97c1-4aff-9a42-19dbbf3e2ad2)
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/58129136/449acc44-f3ee-42b6-90cf-54d9e0fdedca)

**Comment by bsstephan** [comment]
Sorry, I think this is an unfortunate side effect of the swap feature. The option swaps the *function* of the buttons, but the button themselves are the same, and the hotkeys react to the physical button pressed, not the result.

**Comment by jazonandes** [comment]
Understandable. Wish I was smart enough to edit the Web Configurator so that the labels under Hotkey Settings didn't change when Touchpad and Share are switched, but that's beyond me. Thank you for the help!

**Comment by teikai1216** [comment]
#317 will fix the hotkey when you swap the touchpad and share buttons in PS4 mode.

**Comment by bsstephan** [comment]
I left a comment on the PR, I think it's better to wait for a different feature rather than changing the button mapping contributions directly. I can't grok right now if the UI changes still make sense in light of that.

**Comment by TheTrainGoes** [comment]
This has been addressed and merged into main
