### ISSUE TITLE
Get the GitHub actions to correctly build and share the fsdata.c file.

### ISSUE THREAD

**Issue by Fortinbra** [OpenStickCommunity/GP2040-CE#33]
Trigger a build of the WebConfigurator project, and generate a new fsdata.c file, and upload it as an organizational artifact.
Then when GP2040-CE builds, always download latest artifact for fsdata to use in the build.

**Comment by justin-pierce** [comment]
So the idea is that changes to web configurator repo trigger a new fsdata.c build, stored as an artifact in web configurator repo? 

Artifacts from github actions are good for 90 days -- will that potentially be an issue? Also not seeing much info about grabbing artifacts across separate repos. Other approaches might be: 

 - Web configurator builds fsdata.c as releases, GP2040-CE action fetches latest release
 - GP2040-CE uses its own submodule of web configurator to build fsdata.c itself
