### ISSUE TITLE
What is the function of LS/RS TOGGLE ？？

### ISSUE THREAD

**Issue by zzzxiaozheng** [OpenStickCommunity/GP2040-CE#339]
What is the function of LS/RS TOGGLE ？？Can I customize it to other buttons？

**Comment by InfraredAces** [comment]
Please read the [documentation](https://gp2040-ce.info/#/web-configurator?id=joystick-selection-slider).

The LR/RS toggle is meant to toggle between dpad, left stick, and right stick. With dpad being the default.

If you are referring to a toggle on a specific board, speak with the vendor. Please do not use GitHub for asking general questions. Please use the [OpenStick Discord #support channel](https://discord.gg/K6sNzuJR). The maintainers and other community members can provide help and answer your questions there.
