### ISSUE TITLE
HOTKEY_CAPTURE_BUTTON doesn't do anything

### ISSUE THREAD

**Issue by bsstephan** [OpenStickCommunity/GP2040-CE#342]
I noticed this while doing all the other hotkey changes I've been working on, but didn't want to muddle PRs. `case HOTKEY_CAPTURE_BUTTON` doesn't do anything other than `break`.

I'm guessing it should `state.buttons |= options.switchTpShareForDs4 ? GAMEPAD_MASK_A2 : GAMEPAD_MASK_S1`, to reflect how we made the button consistent and pushed the TP/Share toggle into the PS4 report.

**Comment by bsstephan** [comment]
This issue is blocked by #360 as I broke the feasibility of the intended fix.

**Comment by bsstephan** [comment]
Addressed in https://github.com/OpenStickCommunity/GP2040-CE/pull/394 --- just waiting for a release to close this.

**Comment by TheTrainGoes** [comment]
This has been rolled into RC, closing issue
