### ISSUE TITLE
HOTKEY_INVERT_X_AXIS doesn't do anything, never did?

### ISSUE THREAD

**Issue by bsstephan** [OpenStickCommunity/GP2040-CE#361]
Looking at the git history, it seems `HOTKEY_INVERT_X_AXIS` has always just done a `break` and accomplished nothing. I think it could work just like the the other axis, so it was probably just an oversight/thinko.

**Comment by TheTrainGoes** [comment]
Hey @bsstephan - I believe this was due to lack of shortcut keys at the time.

**Comment by bsstephan** [comment]
Makes sense, that'll hopefully not be a problem for much longer. =)
