### ISSUE TITLE
How to flash on ps4 controller ??

### ISSUE THREAD

**Issue by isslam95** [OpenStickCommunity/GP2040-CE#386]
i have ubuntu installed 
do i have to flash it with special usb or can i make flash drive and connect to ds4 with otg to flash

**Comment by InfraredAces** [comment]
That is not within the scope of the project. This firmware is made to run on RP2040 based devices. Please read the documentation at https:gp2040-ce.info for more information and next time to use the appropriate issue template to properly submit issues.
