### ISSUE TITLE
Flatbox bricked

### ISSUE THREAD

**Issue by DasMoks** [OpenStickCommunity/GP2040-CE#390]
Hey guys, just got a new Flatbox that had GP2040-CE installed. Tried to update the firmware and supposedly chose the wrong .uf2 (rev5 when i should have gone rev4 i guess) and kinda bricked my device... Buttons are shifted all around and I can't get into the web configurator to undo my damage... Have any idea how I can save that? Can't access web configurator or Bootsel...
Thanks in advance
Max
EDIT:
There was a button that allowed me to force Bootsel, I found the flash-nuke, but now none of the verisons (0.7.1 since that was the default) works correctly (the board inside this seems to be a custom pcb, named "FightingBox-XLL-rev1.1") and it has a little screen. It was this one from Ali https://de.aliexpress.com/item/1005005514703052.html?spm=a2g0o.order_list.order_list_main.5.21ef5c5f90dj4I&gatewayAdapt=glo2deu  the model with screen and led switches

**Comment by SpoonyAllen** [comment]
download the flash nuke from the downloads section 
https://gp2040-ce.info/#/download

Hold down the BOOTSEL button on your device and plug it in.

Drag the Nuke file into your device and it should erase your old firmware and allow you to start over.

**Comment by DasMoks** [comment]
hey Spoony! Thanks for your reply, I already was able to nuke that, but I can't figure out a firmware that is working... Any ideas? I messaged the seller on Ali to find out which firmware they used, but I am kinda pessimistic about that approach,..
