### ISSUE TITLE
Shortcuts with Keyboard Host Configuration Addon

### ISSUE THREAD

**Issue by InfraredAces** [OpenStickCommunity/GP2040-CE#396]
### Prerequisites

Please check the following before posting an issue / bug report.

- [ ] I am running the latest version of the firmware found [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases)
- [x] I have checked the documentation [HERE](https://gp2040-ce.info/#/) and found no answer
- [x] I checked to make sure that this issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues)
- [x] I am reporting the issue to the correct repository

### Context

* Firmware Version: [CMake #1063](https://github.com/OpenStickCommunity/GP2040-CE/actions/runs/5450365388)
* Name of device: RP2040 Feather USB A Host
* Link to where you purchased the device: https://www.adafruit.com/product/5302
* Is this a custom build?: No
* Operating System: 6.4.1-arch1-1
* Browser: Chromium

### Expected Behavior

Use the Keyboard Host Configuration Addon with the RP2040 Feather USB A Host. Plug a keyboard into the USB A host port, and use the short cuts as one can by manually triggering pins on RP2040 board.

### Current Behavior

Keyboard is working as intended, able to input all commands, but shortcuts do not trigger.

### Steps to Reproduce

1. Flash RP2040 Feather USB A Host with Pico .uf2 file from [CMake #1063](https://github.com/OpenStickCommunity/GP2040-CE/actions/runs/5450365388)
2. Press and hold GPIO 17 (located on USB Host port) and reset to go into WebConfig
3. Disable addons and remap pins appropriately to free up GPIO 16, 17, and 18 for the USB A Host

![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/44279698/56cbb33e-f706-46da-bb28-1a4ad4e8b528)

4. Enable Keyboard Host Configuration
5. Configure the keyboard using the following layout (requires this layout due to issue #395 )

![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/44279698/a7b2d28e-843b-40b8-b2c1-6ab1b2734a84)

6. Set D+ to 16 (Automatically sets D- to 17)
7. Restart Controller
8. Plug in keyboard into USB A Host
9. Attempt to input default shortcuts using keyboard (fails)

**Comment by TheTrainGoes** [comment]
This issue has been resolved and merged in main
