### ISSUE TITLE
Trying to make USB Keyboard Host Work on RP2040

### ISSUE THREAD

**Issue by ez2torta** [OpenStickCommunity/GP2040-CE#400]
### Prerequisites

Please check the following before posting an issue / bug report.

I tried wiring a USB Female port using this schematic

https://user-images.githubusercontent.com/77402236/241382084-8d2a5936-78b6-46ed-bc74-0ec21d629bd6.png

and compiled the latest main branch https://github.com/OpenStickCommunity/GP2040-CE/commit/25604fe4b62de2693724f14817935081da60049f

not working unless i'm missing something :/

- [ ] I am running the latest version of the firmware found [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases)
- [x] I have checked the documentation [HERE](https://gp2040-ce.info/#/) and found no answer
- [ ] I checked to make sure that this issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues)
- [x] I am reporting the issue to the correct repository

### Context

Please provide all relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.  

* Firmware Version: 25604fe4b62de2693724f14817935081da60049f
* Name of device: Raspberry Pi Pico
* Link to where you purchased the device:
* Is this a custom build?: Yes
* Operating System: Linux
* Browser:

### Expected Behavior

I expect the USB Keyboard Host to work before and after RP2040 boot sequence

### Current Behavior

What is the current behaviour?

the keyboard host does not work, if i plug a keyboard before turning on the RP2040 the controller does not show. If i plug the keyboard after the RP2040 is working as a xbox360 controller also does not work.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Wire the female USB as the diagram above
2. Flash the current main branch 
3. use the webconfig for the D+ and D- pins
![imagen](https://github.com/OpenStickCommunity/GP2040-CE/assets/5553942/8a3c3648-da93-458a-8eba-6f9a4275d5df)
4. Keyboard not recognized. board not working if usb device is plugged

### Screenshots & Files

Please include any relevant screenshots or files here.  If you are having issues with a board please include images of the front and back of the board.

**Comment by arntsonl** [comment]
Which keyboard are you using? I found that some keyboards with non-generic HIDs do not work such as Razer, while others work fine.

**Comment by ez2torta** [comment]
I tried a taser keyboard but also a HP keyboard and a Kensington keyboard and none of them worked. 

I'm kinda worried that the rp2040 does not boot correctly when I have the usb keyboard connected. Is that expected?

**Comment by ez2torta** [comment]
Now tried with the latest RC firmware and same results.. should i use certain pins for the D+ and D- wires?

**Comment by TheTrainGoes** [comment]
Hi @ez2torta ,

Due to some ongoing concerns around USB host mode we have removed it from the current build.  You are welcome to continue exploring it on your own or join up on the Discord and see if there is anyone else that can try to assist.
