### ISSUE TITLE
Additional hotkey options (L3, R3, Touchpad)

### ISSUE THREAD

**Issue by ccristob** [OpenStickCommunity/GP2040-CE#424]
### Have you checked the GP2040-CE documentation [HERE](https://gp2040-ce.info/#/) to confirm this feature doesn't already exist?

Yes

### Which problem is this feature request solving?

I'm currently using older sticks that do not have dedicated buttons for L3, R3 and a Touchpad and would like to use button combinations on the existing buttons that are on the stick to trigger L3, R3 or Touchpad instead.

### Describe the solution you would like to see

Expand the Hotkeys section in the web configurator to also be able to map hotkeys to L3, R3 and Touchpad.

### Describe alternatives you've considered

Hardware mods such as drilling new holes to add more buttons, but I don't want to ruin the stick's aesthetics and would prefer to leave it as is.

### Can you submit a pull request?

Yes.

### Are you planning on working on this feature yourself?

No.

**Comment by bsstephan** [comment]
This would be a relatively easy change for anyone, but note to myself: it might also be a good impetus for doing my "pushing state to the report" change that I think ought to get done at some point.
