### ISSUE TITLE
Build makefsdata from source, rather than checking in binaries

### ISSUE THREAD

**Issue by micolous** [OpenStickCommunity/GP2040-CE#432]
### Have you checked the GP2040-CE documentation [HERE](https://gp2040-ce.info/#/) to confirm this feature doesn't already exist?

Yes

### Which problem is this feature request solving?

At the moment, there are *compiled*, mono-architecture (`amd64`) binaries checked in to the repository for Linux, macOS and Windows (`tools/makefsdata*`) which are a critical part of the build process.

There are [currently build instructions for Raspberry Pi](https://gp2040-ce.info/#/development?id=linux-setup-raspberry-pi), but they won't work without setting up userspace `amd64` binary emulation (which will be slow).

Currently, only the Linux binary has reproduction instructions (`tools/linux_compile_makefsdata.sh`), but it still requires additional manual steps to complete (ie: is not [deterministic](https://en.wikipedia.org/wiki/Reproducible_builds)).

There seems to be some history in the project with the issue where the binaries were not completely portable - so building this from source would be more portable too!

### Describe the solution you would like to see

The build scripts should build `makefsdata` from source, using the host's compiler.  You already need to pull in the Pico SDK to build the rest of the project, which includes `lwip`'s `makefsdata.c`.

This way, `makefsdata` will always be a native binary built _only_ with artefacts on the developer's machine, and properly reproducible.

Here's a `CMakeLists.txt` which works on Linux (based on `tools/linux_compile_makefsdata.sh`), which uses the default compiler, and system `zlib` (rather than needing to pull in `miniz`).

```cmake
cmake_minimum_required(VERSION 3.10)
project(makefsdata VERSION 1.0)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

include(FindZLIB)

add_executable(makefsdata
        "$ENV{PICO_SDK_PATH}/lib/lwip/src/apps/http/makefsdata/makefsdata.c")

target_link_libraries(makefsdata ZLIB::ZLIB)

target_include_directories(makefsdata PUBLIC
        "$ENV{PICO_SDK_PATH}/lib/lwip/src/include"
        "$ENV{PICO_SDK_PATH}/lib/lwip/contrib/ports/unix/lib"
        "$ENV{PICO_SDK_PATH}/lib/lwip/contrib/ports/unix/port/include")

target_compile_definitions(makefsdata PUBLIC
        MAKEFS_SUPPORT_DEFLATE
        MAKEFS_SUPPORT_DEFLATE_ZLIB)
```

With a little polish and using [`add_custom_command()`](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Custom%20Commands.html#using-an-executable-to-build-a-source-file) to build `fsdata.c` (replacing `makefsdata.js`), it could be properly integrated into the build, including handling updates in a sensible way (ie: only when the source files change).

Relatedly, the existing build setup appears to drop JavaScript build artefacts in the _source_ directory (`www/build`), rather than using CMake's `build` directory ([`PROJECT_BINARY_DIR`](https://cmake.org/cmake/help/latest/variable/PROJECT_BINARY_DIR.html)), which means those artefacts are not properly isolated (two different `build` directories will affect each other).

### Describe alternatives you've considered

Executing arbitrary unsigned binaries uploaded by "some person", which aren't [completely reproducible](https://en.wikipedia.org/wiki/Reproducible_builds).

### Are you planning on working on this feature yourself?

I was evaluating GP2040-CE for a project idea, and hit this roadblock trying to build this from source.

I'm happy to consult as needed, but due to chronic `nodejs`/`npm` allergies, I can't make "the complete thing" work.

**Comment by arntsonl** [comment]
For local builds, if you are uncomfortable with running makefsdata.exe/makefsdata.darwin, it should be relatively straight forward to compile your own binaries. Building/debugging on Windows requires a lot of other .exe's including picotool and SDK tools, so we are comfortable with providing pre-built binaries for Windows/Mac. The github actions handles building our fsdata.c and pushing these changes to the uf2s for release, so we are comfortable with this build process.

Additionally, nodejs/npm is a dependency we are very comfortable with and we will be keeping this going forward.
