### ISSUE TITLE
Issue - Navigating directly to pages error in web-config

### ISSUE THREAD

**Issue by arntsonl** [OpenStickCommunity/GP2040-CE#441]
### Prerequisites

Please check the following before posting an issue / bug report.

- [DEV] I am running the latest version of the firmware found [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases)
- [x] I have checked the documentation [HERE](https://gp2040-ce.info/#/) and found no answer
- [x] I checked to make sure that this issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues)
- [x] I am reporting the issue to the correct repository

### Context

Please provide all relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.  

* Firmware Version: Latest-main
* Name of device: RP2040 test board
* Link to where you purchased the device:
* Is this a custom build?:
* Operating System:
* Browser: Chrome

### Expected Behavior

Navigating directly to http://192.168.7.1/profile-settings should display fine.

### Current Behavior

Navigating directly to http://192.168.7.1/profile-settings results in a cannot display (as well as potentially other pages)

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Reboot device into web configurator
2. Navigate to http://192.168.7.1/profile-settings
3. Observe the page does not load

**Comment by TheTrainGoes** [comment]
This has been addressed and merged into main
