### ISSUE TITLE
Splash Screen: Mismatch of options in Web Config / Board Config / Enums.proto

### ISSUE THREAD

**Issue by HoboDev** [OpenStickCommunity/GP2040-CE#455]
### Prerequisites

Please check the following before posting an issue / bug report.

- [x] I am reporting the issue to the correct repository

### Context

Please provide all relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.  

* Firmware Version: 0.7.3 (applies to other versions, too)

### Issue Description

The mentioned options in all(?) ```BoardConfig.h``` files  does not match with the other entries. (But it does with ```config_legacy.cpp```)
~~```config_legacy.cpp```: iirc enums start at 0~~
```DisplayConfig.jsx```: options missing, names of defines differ
```enums.proto```: ~~numbers and~~ names of defines differ

edit: After looking at the SOCD default options it occurred to me that the ```BoardConfig.h``` just numbers the options instead of implying the values. This is still a bit confusing and the number could just be removed as it doesn't serve any purpose or helps with explanations.

I recommend to reference the ```enum SplashMode``` in ```enums.proto``` in each ```BoardConfig.h``` reducing maintenance. Another recommendation is to remove noise from the comments:

Example:

```
// Current options for `SPLASH_MODE` (default: `SPLASH_MODE_NONE`):
// `STATIC` - Displays static splash for `SPLASH_DURATION`
// `CLOSEIN` - Animation of static splash from top and bottom to center.
// `CLOSEINCUSTOM` - Same as `CLOSEIN` with custom splash.
// `NONE` - Disables splash on boot.
```

### Screenshots & Files

```BoardConfig.h```
```
// There are four options for `SPLASH_MODE` currently:
// 1 - `STATICSPLASH` - This will display the static splash image
// 2 - `CLOSEIN` - This will display the static splash image as a top and bottom coming together animation
// 3 - `CLOSEINCUSTOM` - This will display the custom splash image as a top and bottom coming together animation
// 4 - `NOSPLASH` - This will not display a splash screen on boot
```

```config_legacy.cpp```
```
enum SplashMode
    {
        STATICSPLASH,
        CLOSEIN,
        CLOSEINCUSTOM,
        NOSPLASH,
    };
```

```DisplayConfig.jsx```
```
const SPLASH_MODES = [
	{ label: 'Enabled', value: 0 },			 // STATICSPLASH
	//	{ label: 'Close In', value: 1 },		 // CLOSEIN
	{ label: 'Disabled', value: 3 },         // NOSPLASH
];
```

```enums.proto```
```
enum SplashMode
{
    option (nanopb_enumopt).long_names = false;

    SPLASH_MODE_STATIC = 0;
    SPLASH_MODE_CLOSEIN = 1;
    SPLASH_MODE_CLOSEINCUSTOM = 2;
    SPLASH_MODE_NONE = 3;
}
```

**Comment by TheTrainGoes** [comment]
Hey @HoboDev ,

This needs some cleanup for sure.

There are some things in here that we currently do not have in web-config like a top.bottom drop in animation on boot.

**Comment by mikepparks** [comment]
Some adjustments were made to bring these modes back in v0.7.8.
