### ISSUE TITLE
Reupload the SVG logo now that license issues are settled

### ISSUE THREAD

**Issue by nilleairbar** [OpenStickCommunity/GP2040-CE#466]
See title :)

**Comment by TheTrainGoes** [comment]
@nilleairbar as an update on this I reached out and purchased a proper license for the font used in the logo and should be getting the official paperwork mid-September. 

Once that is done I will add all of the logo and fonts in.

**Comment by TheTrainGoes** [comment]
@nilleairbar this has been merged as part of https://github.com/OpenStickCommunity/Hardware/pull/59
