### ISSUE TITLE
Bounty - Change display layout structure from calculation to exact positioning and size

### ISSUE THREAD

**Issue by TheTrainGoes** [OpenStickCommunity/GP2040-CE#48]
Currently we use a strange string of calculations to size and position inputs on the screen.  This appears to be dynamic so I am guessing it was intended for displays that were in non-standard sizes.  

I would like to see this changed to absolute positioning + size.  

An example:

Button K1 (8, 20, 40)
Radius = 8 pixles
X location = 20 pixles
Y location = 40 pixles

**Comment by FeralAI** [comment]
> 

The original intent was to be able to scale all the screen assets for whatever resolution display is being used, with the goal of using things like 256x64 OLEDs and the 2.7" Sharp 400x240 monochrome screens. The dynamic sizing is probably more useful if we're basing things on aspect ratio vs. resolution.

I suggest we define a "stylesheet" for all the screen elements which will contain position, dimensions and font styling. Then we can add in more target resolutions that are supported by the drivers in the OneBitDisplay library if desired.

**Comment by TheTrainGoes** [comment]
Going to close this for now and re-open as a bounty with some different asks
