### ISSUE TITLE
Swith Pro controller replacement PCB

### ISSUE THREAD

**Issue by NickGuyver** [OpenStickCommunity/GP2040-CE#516]
### Have you checked the GP2040-CE documentation [HERE](https://gp2040-ce.info/#/) to confirm this feature doesn't already exist?

Yes

### Which problem is this feature request solving?

Get game pads running GP2040-CE.

### Describe the solution you would like to see

Looking for a custom PCB running GP2040-CE that can be swapped into a Switch Pro controller shell. I believe this is a perfect base for doing a game pad since it's only 4 analog axis, as the triggers are digital and their own PCB. Additionally, the shells, membranes, buttons, and supplementary PCBs are readily available. BT is still in-progress on the firmware side and is not within scope here.

### Describe alternatives you've considered

Found PhobGCC v3 but it's not open source.

### Can you submit a pull request?

No

### Are you planning on working on this feature yourself?

No

**Comment by TheTrainGoes** [comment]
This is resolved since a board already exists
