### ISSUE TITLE
Can not join discord

### ISSUE THREAD

**Issue by Joomaton** [OpenStickCommunity/GP2040-CE#519]
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/145011657/e00de621-599d-4826-a59d-19d8d654e82d)

**Comment by Pelsin** [comment]
Hi! Sorry to hear you are having trouble joining the discord.
What link did use, was it https://discord.gg/k2pxhke7q8?

It might also be that a phone verification is required: https://support.discord.com/hc/en-us/articles/6181726888215-Verification-Required-FAQ

If it still does not work, try opening the invite link in an incognito window.

**Comment by Joomaton** [comment]
Yes. That's the link I've used.
Phone verification would be odd. I never did that but I can chat on other channels without any issue.
I hope discord is not turning google.

**Comment by TheTrainGoes** [comment]
Hi @Joomaton ,

There was a period of time recently where we had entrance screen set to the highest.  It has been lowered a little.  

If you are still unable to join then your account does not meet our criteria for entry.
