### ISSUE TITLE
XInput Not registering L2/R@

### ISSUE THREAD

**Issue by manianiac** [OpenStickCommunity/GP2040-CE#525]
* Firmware Version:  Action#1636
* Name of device: Pico Fighting Board Ultimate Edition
* Link to where you purchased the device: https://www.etsy.com/listing/1495412189/pico-fighting-board-type-c-ultimate?show_sold_out_detail=1&ref=nla_listing_details
* Is this a custom build?: 
* Operating System: Windows
* Browser: Chrome

### Expected Behavior

L2 and R2 buttons to register to Gamepad Tester

### Current Behavior

Neither button registers on Gamepad Tester

### Steps to Reproduce

Map button to L2/R2
Load Gamepad Tester
Verify any other button works as expected
Press L2/R2

I was able to get the buttons to work in anything other than XInput mode

**Comment by TheTrainGoes** [comment]
Hi @manianiac ,

Please reach out to the maker of the Pico Fighting Board Ultimate Edition for support on this issue.

There are no issues with L2/R2 in our current v0.7.4 firmware in Xinput mode.
