### ISSUE TITLE
4-Way Joystick Mode behaves differently from expectation

### ISSUE THREAD

**Issue by sirrow** [OpenStickCommunity/GP2040-CE#532]
### Prerequisites
- [x] I am running the latest version of the firmware found [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases)
- [x] I have checked the documentation [HERE](https://gp2040-ce.info/#/) and found no answer
- [x] I checked to make sure that this issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues)
- [x] I am reporting the issue to the correct repository

### Context
* Firmware Version: v0.7.4
* Name of device: Pico (but the issue should be not depend to device.)
* Is this a custom build?: no

### Description of Issue

I found 4-Way Joystick Mode behaves differently from my expectation.
It seems for me that SOCD and 4-Way Joystick Mode seems conflicted and 4-Way Joystick Mode need to care only diagonal direction but also opposite direction.
It would be grateful if some of you consider if my expectation reasonable.
2 examples I feel strange are below.

##### Preconditions
- SOCD is Last Win
- 4-Way Joystick Mode is enabled

##### Scenario
1. push left
2. push right
3. push down
4. release right

##### Expected Output
down is pressed

##### Actual Output
left is pressed because SOCD outputs left at step 4 and 4-Way Joystick Mode get output of SOCD.

##### Preconditions
- SOCD is Off
- 4-Way Joystick Mode is enabled

##### Scenario
1. push left
2. push down
3. push right

##### Expected Output
right is pressed

##### Actual Output
Both left and right are pressed. Because 4-Way Joystick Mode only seems only checking which of directions which consists diagonal is pressed last and SOCD is Off.

**Comment by sirrow** [comment]
Examples are checked in below environment:
- Input Mode in GP2040-CE
  - Xinput
- gamepad tester (reproduced in both web site)
  - https://hardwaretester.com/gamepad
  - https://pelsin.github.io/gamepad-tester/
- Browser
  - Chrome
- OS
  - Windows 11

**Comment by bsstephan** [comment]
@sirrow - if you get a chance can you try my changes in https://github.com/OpenStickCommunity/GP2040-CE/compare/main...bsstephan:GP2040-CE:four-way-improvements ? I have 4-way running before SOCD now, and it makes Example 1 work as expected. I'm wondering if you can try it out and make sure it didn't break some other expectation, but it looks good to me. I do not know if it addresses Example 2 at all.

**Comment by bsstephan** [comment]
Oh, found a new breakage, now Example 1 is fixed, but if you instead do Left, Down, Right you get... nothing. Wild. Well I'll mess with it more later.

**Comment by bsstephan** [comment]
Okay. I think @sirrow's branch fixes my issue. Assuming @TheTrainGoes can confirm that #533 fixes the SOCD=Off case, my testing suggests we should merge both #533 and #537.

**Comment by sirrow** [comment]
I tested code on my testing branch merging both #533 and #537.
With the branch, both examples got result as my expectation.
I cannot find any flaw about 4-Way Joystick Mode from test and logic point of view in case both https://github.com/OpenStickCommunity/GP2040-CE/pull/533 and https://github.com/OpenStickCommunity/GP2040-CE/pull/537 are merged.
