### ISSUE TITLE
How can I change the default xinput_string_product whose default value is "XInput STANDARD GAMEPAD"

### ISSUE THREAD

**Issue by zeyingzheng-linux** [OpenStickCommunity/GP2040-CE#592]
### Environment
* Firmware Version: v0.7.1 and I add some code by myself to change xinput_string_product
* Name of device: PicoFightingBoard
* Is this a custom build?: Yes , I add some code by myself to xinput_string_product
* Operating System: Ubuntu 20.04
### Expected Behavior
*  xinput_string_product can be changed in PicoFightingBoard

### Current Behavior
* xinput_string_product can not be changed in PicoFightingBoard

![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/54948022/0914efe4-afad-41cc-b454-3268351f47b5)

![bc7a803520903db6b8b1ed55aa959f3](https://github.com/OpenStickCommunity/GP2040-CE/assets/54948022/6bfd8fd8-09e1-4fbb-99f4-892228870db8)

I find the Controller descriptor string always  "XInput STANDARD GAMEPAD"，although I change it in my code.  I also flash flash_nuke.uf2 file every time I flahs my own uf2 file.

**Comment by TheTrainGoes** [comment]
Hi @zeyingzheng-linux ,

Changing line 51 in XInputDescriptors.h does change it but some programs and applications will still show the generic listing.  

As an example, I updated it to `TEST` and https://hardwaretester.com/gamepad still shows it as:
Xbox 360 Controller STANDARD GAMEPAD 

In Mac terminals it shows up as:
XInput TEST:
  Product ID:	0x028e
  Vendor ID:	0x045e  (Microsoft Corporation)
  
 You may get further by changing the PID and VID.  I am going to close this issue.

**Comment by zeyingzheng-linux** [comment]
> Hi @zeyingzheng-linux ,
> 
> Changing line 51 in XInputDescriptors.h does change it but some programs and applications will still show the generic listing.
> 
> As an example, I updated it to `TEST` and https://hardwaretester.com/gamepad still shows it as: Xbox 360 Controller STANDARD GAMEPAD
> 
> In Mac terminals it shows up as: XInput TEST: Product ID: 0x028e Vendor ID: 0x045e (Microsoft Corporation)
> 
> You may get further by changing the PID and VID. I am going to close this issue.

Thanks for your reply.
I don't think the problem is the programs and applications show the generic listing.
I find windows show the string  "GP2040-CE(PS4)" or "XIput STANDARD GAMEPAD" or the other string .  If windows show the generic listing via PID/VID ，GP2040 device must regisgter in USB-IF (https://www.usb.org/). I think the string descriptor must transfer by GP2040 device.

Is it possible save the string descriptor in other flash region but not code region, so my modified code didn't work . 
Could you give me some suggestion.

**Comment by TheTrainGoes** [comment]
Hi @zeyingzheng-linux ,

We have no plans to change the location of this code at this time.  

May I ask what the use case is for changing this?

**Comment by zeyingzheng-linux** [comment]
> Hi @zeyingzheng-linux ,
> 
> We have no plans to change the location of this code at this time.
> 
> May I ask what the use case is for changing this?

I just change the code then try to understand the code logic , and I find it go against my understanding. 
I do this for the purpose of showing my personal string when I plug the GP2040 device .
Finally , I can change the code by myslef , I just want to know why it cann't work when I change the string descriptor .Could you tell me why ?

**Comment by TheTrainGoes** [comment]
That is correct, however it would rely on the person never having plugged in a device with that generic PID/VID/Name descriptor.
