### ISSUE TITLE
Give the Function Key the possibility to send Keyboard Presses

### ISSUE THREAD

**Issue by Reaper2507** [OpenStickCommunity/GP2040-CE#601]
### Have you checked the GP2040-CE documentation [HERE](https://gp2040-ce.info/#/) to confirm this feature doesn't already exist?

Yes

### Which problem is this feature request solving?

Xbox Controler has only 14 Buttons but i want to use 15 (like PS5 Pad with Touchpad button)
Games sometimes require some Keyboardpresses and combining them with the X-Input allows for a really good PadInteraction

### Describe the solution you would like to see

Provide a Action like "SendKEys/String" in this dropdown menu with Modfiers like "windows/strg/alt" that would allow to make shortcuts like Windows+G on a PS4 pad or spezific keys like "F" for streetfighter or much more 
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/89843872/1b0e4e3b-aa8d-44ef-bdf3-ad4d1637332a)

this would allow a PS4 input with a Microsoft Homebutton as example by sending windows + G for the microsoft gamebar)
that in itself would allow to use ps4 better on pc

### Describe alternatives you've considered

allow mapping of PS4 or Switchbuttons in the Xinput and vis versa (not as good as and some games would not support this anyway)

### Can you submit a pull request?

No.

### Are you planning on working on this feature yourself?

No.

**Comment by TheTrainGoes** [comment]
Hi @Reaper2507 ,

At this time we have no plans to introduce mixed input modes.  

I will close this off as not planned which can always be revisited in the future.
