### ISSUE TITLE
Issue when Saving Macros

### ISSUE THREAD

**Issue by ZoddoDK** [OpenStickCommunity/GP2040-CE#622]
I am running version Pico Fighting Board (GP2040-CE_0.7.5_PicoFightingBoard.uf2)

When i want to save any Settings on the Macro Page via the Save button nothing is happening and the settings are apparently not saved.
If I refresh the page after, everything is back to the Default Settings.

**Comment by ZoddoDK** [comment]
I double checked again, this time I assigned a Macro to Pin 21, which I double checked to not be assigned anywhere in the Pin mapping, and I still have he same result.
When I bind Pin 21 in Pin Mappings to L3 it works just fine.

**Comment by TheTrainGoes** [comment]
Please take a screen shot of your Macro setup prior to attempting to press the save button.  

Also please let us know what device you are trying to do this on and include a copy of your backup file.   

If you are on the Discord it may be easier to file a ticket there.

**Comment by ZoddoDK** [comment]
![image_2023-12-05_112126594](https://github.com/OpenStickCommunity/GP2040-CE/assets/138272109/ce154bb3-5658-4228-a448-6705bcc8e1ff)
![image_2023-12-05_112248662](https://github.com/OpenStickCommunity/GP2040-CE/assets/138272109/f38d681a-db9b-4340-9c65-84d681c46c73)
Now i press Save. No Message or anything appears.
After I refresh the Page looks like this:
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/138272109/4ba0673c-8d54-4ef4-9501-c8b20161347c)

**Comment by ZoddoDK** [comment]
[gp2040ce_backup_20231205042415855.zip](https://github.com/OpenStickCommunity/GP2040-CE/files/13555100/gp2040ce_backup_20231205042415855.zip)

**Comment by ZoddoDK** [comment]
The device is a Pico Fighting Board

**Comment by TheTrainGoes** [comment]
In that screen shot you have not activated the macro.  Please try activating the macro

**Comment by ZoddoDK** [comment]
![image_2023-12-05_180318606](https://github.com/OpenStickCommunity/GP2040-CE/assets/138272109/9d476bc4-3903-4258-b37a-2783140ff0d0)
That doesn't seem make any difference, settings still will not get saved when I press the save Button.

**Comment by TheTrainGoes** [comment]
I loaded your backup and it appears there was some sort of saved pin issue on pin 20 and 21.  

I was able to do the following with your backup to resolve:

1 - Nuke
2 - Load PFB UF2
3 - Load your backup
4 - Change the extra button pin from 20 to -1, then disable and save
5 - Setup the macro on pin 21 and save
6 - Turn back on the extra button pin on 20 and save

I was also able to do this on a fresh install of the firmware directly after a nuke.

**Comment by ZoddoDK** [comment]
Thanks for all the effort. I will give that a try.

**Comment by ZoddoDK** [comment]
I did everything as described but still have the same issue. The only thing I wasn't sure about was the "Nuke" part. What I did was Boot in "USB (BOOTSEL)" and then I reinstalled "GP2040-CE_0.7.5_PicoFightingBoard.uf2". Does that count as a "Nuke"?
Afterward I did 3-4-5-6 with the same result in the end.

**Comment by ZoddoDK** [comment]
OK I will try that. Thanks.

**Comment by ZoddoDK** [comment]
Thanks, a lot. That did the trick.
