### ISSUE TITLE
I want to know how to get the debug log from pico because that use tiny usb and can not  use pico_enable_stdio_usb(${PROJECT_NAME} 1)

### ISSUE THREAD

**Issue by chenxixingtt** [OpenStickCommunity/GP2040-CE#640]
I want to know how to get the debug log from pico because that use tiny usb and can not  use pico_enable_stdio_usb(${PROJECT_NAME} 1)

**Comment by Fortinbra** [comment]
This sounds more like a question for the pico sdk project.

**Comment by TheTrainGoes** [comment]
Closing due to no reply
