### ISSUE TITLE
Bug for macro failure when setting multiple macros

### ISSUE THREAD

**Issue by wowplayhitbox** [OpenStickCommunity/GP2040-CE#704]
Prerequisites
Please check the following before posting an issue / bug report.

 I am running the latest version of the firmware found [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases)
 I have checked the documentation [HERE](https://gp2040-ce.info/) and found no answer
 I checked to make sure that this issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues)
 I am reporting the issue to the correct repository
* Firmware Version:[v0.7.6-RC2](https://github.com/OpenStickCommunity/GP2040-CE/releases/tag/v0.7.6-RC2)
* Name of device:GP2040-CE_0.7.6_Haute42.uf2
* Browser:chrome

When setting multiple macros, the triggering of the macro will fail. It will be valid for a while and invalid for a while. When only one macro is set, the triggering of the macro is completely normal.

http://192.168.7.1/macro
![20231225080142](https://github.com/OpenStickCommunity/GP2040-CE/assets/154765649/fc785405-a0f3-4763-92e8-f351cac47fb4)

https://github.com/OpenStickCommunity/GP2040-CE/assets/154765649/b8e099e2-42cd-4b86-be67-5e86932904c2

**Comment by fvolpe83** [comment]
same here, tested both with macro button pin and without:
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/62909893/73365129-f5ff-44c4-8488-4448260191dd)
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/62909893/be4f1bb9-322f-454d-9550-cb35998ac754)
as soon as the second macro is triggered, the first one becomes unavailable in both cases

**Comment by fvolpe83** [comment]
added a third macro and nullifies the other two, looks like once the latest one gets used once, the others can't

**Comment by alvarodiegomaia** [comment]
I got the same problem and posted it in the haute42 discord.

**Comment by somerandomguy09** [comment]
I'm also afflicted by the same bug; as [fvolpe83] says. The moment the newest macro is triggered all previously assigned macros stop working. 

I'm on firmware 0.77.  Device is Haute42 T16. 

I've tried playing with the interruptible and exclusive settings with no luck either. For now I'm stuck only utilizing one macro at a time

**Comment by WalkWithBlade** [comment]
I got the same problem!

**Comment by InfraredAces** [comment]
Interesting. Given 2 macros, A and B as configured in the image below. 

If you press A, then pressing B won't work. However, if you press A while holding B, A will be triggered, then B will be triggered and B will be the only macro to work. You can do the reverse to change A back to being the only working macro.

If you press A and B rapidly (either alternating or one multiple times then the other), both will work, but if you stop, the last one you pressed will be the only one that works. Until you do any of the above listed steps.

![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/44279698/2de724cb-767e-4d4e-a79c-8bdf854ba9c2)

**Comment by TheMasterPrawn** [comment]
Same problem here. The interface is kinda confusing. But I started to get teh hang of it. It will only ever run the first Macro for me though. 
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/7848415/57bdcf46-d9ec-4e8f-aadd-b1a9b3c902fe)

Surely there must be more people having this problem ? Do we revert firmware to fix for now ?

**Comment by TheTrainGoes** [comment]
This has been addressed in v0.7.8

**Comment by wowplayhitbox** [comment]
This issue has been fixed by new version. I downloaded the version here and verified that it is completely normal.
https://github.com/OpenStickCommunity/GP2040-CE/actions/runs/8501274945#artifacts

**Comment by TheTrainGoes** [comment]
Closing this issue - resolved
