### ISSUE TITLE
Can we add eight directions

### ISSUE THREAD

**Issue by TianMaiChengGhostRidder** [OpenStickCommunity/GP2040-CE#705]
Can we add eight directions, such as bottom left, top left, bottom right, and top right? Because some games are very convenient to use these directions

**Comment by bsstephan** [comment]
This might be possible after #724.

**Comment by bsstephan** [comment]
@TianMaiChengGhostRidder in the next release of the firmware, it will be possible to map multiple outputs, such as Down+Right, to one pin. This should satisfy your request.
