### ISSUE TITLE
Account Banned in Discord

### ISSUE THREAD

**Issue by TitaniumRavage** [OpenStickCommunity/GP2040-CE#723]
Hi,
    I hope you're all good and well. I joined your community in discord with account id Hotshot9449. Without violating or notification I got ban. The next day I inquire about this action one of your senior members with my second account. Without any response or explanation, my second account got banned. Could you please state the reason what did I violate that i got ban?
Thank you

**Comment by mikepparks** [comment]
This is not the proper forum for unban requests. Closing this issue.
