### ISSUE TITLE
Update BoardConfig.h "spec" to do button mapping by pin

### ISSUE THREAD

**Issue by bsstephan** [OpenStickCommunity/GP2040-CE#739]
The GPIO mapping refactor means that protobuf can assign any pin to any button, but the refactor did not update BoardConfig.h because it was too much change all at once. Now that the refactor is settling in 0.7.6, we think we should tackle the BoardConfig.h and change the button/extra defines to instead be pin defines, so that any combination of one to many buttons can be expressed in the base configs.

The thought right now is just to simply have a define for each of `PIN_00` through `PIN_29` in some fashion, probably assigning them directly to `GpioAction`s?

**Comment by TheTrainGoes** [comment]
This has been completed and is in main.
