### ISSUE TITLE
Xbox Series X Automatically Turns Back On After Soft Power Down

### ISSUE THREAD

**Issue by arobotbitme** [OpenStickCommunity/GP2040-CE#749]
**Steps/issue**:
1. Soft shutdown of Xbox Series X using GP2040 controller (details below) by holding Home/Guide and selecting the shutdown option. 
2. System powers down 
3. System immediately automatically boots back up as long as GP2040 controller remains plugged in

**Troubleshooting & Workarounds**:

-Going into the Series X **Settings > General > Power options > Shutdown now > Shut Down** does not seem to trigger the reboot loop issue at all. Good workaround for now. EDIT: Nevermind, the system will eventually turn back on if the controller remains plugged in.

-Tried disconnecting the controller by pulling the USB cable out while the system is shutting down. System does not turn back on when controller is not present during shutdown. 

-If I plug the controller back in after waiting about a minute, it will **not** automatically turn the Xbox Series X back on immediately, but instead will power it on some hours later. System will then eventually shut down due to inactivity only to be immediately woken back up by the controller, a cycle that runs indefinitely. 

-No similar issue on PS4. I feel like this could be a problem with the Magic X's Bluetooth capacity specifically, since, AFAIK, wired controllers can't power the console on.

-All other functionality normal across all tested platforms including Series X 

**Firmware and Hardware Details:**
Xbox Series X
GP2040, 0.76 FW
Fightbox
Raspberry Pi Pico
Homemade passthrough "board" using the female end of a USB extender and 22ohm resistors (hasn't given me a problem before) 
Magic X Wireless Converter FW 1.08 connected to GP2040 pass-through
Pass-through D+ on pin 14, D- on 15, powered by VBUS
Both PS4 Pass through and Xbox One Pass through options turned on in web configurator

**Comment by TheTrainGoes** [comment]
Hi @arobotbitme ,

Thank you for the report.  We will take a look into this but the solution may just be to unplug the controller while turning the system off and plug it back in after the ssytem has been turned back on.

**Comment by arntsonl** [comment]
I think 0.7.9 will fix this :O

**Comment by TheTrainGoes** [comment]
This issue is fixed as of v0.7.9
