### ISSUE TITLE
Using GP2040 as a controller adapter for using 3rd party controllers on all consoles

### ISSUE THREAD

**Issue by smahdink** [OpenStickCommunity/GP2040-CE#784]
### Have you checked the GP2040-CE documentation [HERE](https://gp2040-ce.info/) to confirm this feature doesn't already exist?

Yes

### Which problem is this feature request solving?

I have a let's say Xbox controller and I want to use it on my PS4, currently the only way is to buy one of those adapters like 8bitdo's or to use remote play. The GP2040 I think currently has all the requirements to do this, like USB host mode and integration with various consoles.

### Describe the solution you would like to see

The 3rd party controller would be connected through USB host mode to the PICO, The input from the controller then would be translated to the target platform by reading the inputs from host and mapping it to GP2040 inputs. Authentication is also possible through the add-ons.

### Can you submit a pull request?

No. Unfortunately, I don't have enough knowledge to do that, but I can help test it.

**Comment by TheTrainGoes** [comment]
Hi @smahdink ,

JFedor already has a solution for this you can read about here:
https://github.com/jfedor2/hid-remapper

At this time we don't have immediate plans to have this included in our firmware.
