### ISSUE TITLE
JS Selection Slider debouncer somehow causes LS (default) and RS (pin mapping) to oscillate at debounce time

### ISSUE THREAD

**Issue by bsstephan** [OpenStickCommunity/GP2040-CE#790]
> so if I have default let to LS, buttons set to DP and RS, if I hold the DP button the lever always registers DP (as expected), if I hold the RS button the lever seemingly randomly oscillates between registering LS and RS (I say randomly because it's not entirely even, I think it's picking RS most of the time)
> this is the same as what IA reported
> if I recompile with `#define JSLIDER_DEBOUNCE_MILLIS 0`, no oscillation, RS button works as it should
> so something in the addon's debouncer is acting strange
> going to try a huge value and see what happens
> yup
> if I set it to 250ms, I see LS activating far less in my tester
> I'm only eyeballing it, but I could believe it's 4 times a second
> so something in the debouncer is momentarily setting the mode back to LS
> I'm in the middle of trying another thing (and I guess figuring out why my webconfig is crashy, so two things), so I can't look at that code right now, but I would look at the bitwise operations inside `if ((uNowTime - uDebTime) > JSLIDER_DEBOUNCE_MILLIS)`

**Comment by djbigbear** [comment]
I have mine set DP as default.
the LS slider works fine, DP slider works fine, but the RS inputs both LS and RS rapidly.
