### ISSUE TITLE
Web configuration not opening

### ISSUE THREAD

**Issue by Barrone123** [OpenStickCommunity/GP2040-CE#80]
When I plug in the board, my computer detects it as a POKKEN CONTROLLER, and I can't seem to open the web configuration to change the mappings.
![image](https://user-images.githubusercontent.com/82493907/216765444-abd2b810-5298-4baa-8b44-d1bf1f8d7355.png)
![image](https://user-images.githubusercontent.com/82493907/216765499-39695a37-c814-4cd4-a35e-88ffc6a3b732.png)

**Comment by TheTrainGoes** [comment]
Hi @Barrone123 ,

This would indicate it is in Nintendo Switch mode.  

Have you read the documentation on changing controller modes by pressing a button on plug-in?

www.gp2040-ce.info

**Comment by Barrone123** [comment]
Hello @TheTrainGoes , 

Yes, I've tried doing that, but it still does not work. However, I have already fixed the issue with the Pokken controller by nuking the pico and re-installing the code. Probably the worse way to do it, but it got the job done. 

I'll try again later, as I'm already using it to play games on my PC. Thank you for the comment!

**Comment by TheTrainGoes** [comment]
Hi @Barrone123 ,

Please let me know if this is still an issue, otherwise I can close it.

Thanks!

**Comment by TheTrainGoes** [comment]
Closing - will re-open if we can verify issue on most recent build.
