### ISSUE TITLE
Add a label to pin mapping profile number

### ISSUE THREAD

**Issue by damienleger** [OpenStickCommunity/GP2040-CE#807]
### Have you checked the GP2040-CE documentation [HERE](https://gp2040-ce.info/) to confirm this feature doesn't already exist?

Yes

### Which problem is this feature request solving?

Avoiding to remember which profile corresponds to each game/device. Prevent mistake of selecting the wrong profile. Better UX/QoL for gamer.

### Describe the solution you would like to see

(proto with copy/paste & F12 live edit on v0.7.7 interface)

My idea is to add an optional "label" input on each profile on pin mapping setting (same as the one in macro settings page)

![2024-01-19 07_24_37-GP2040-CE Configurator — Firefox Nightly](https://github.com/OpenStickCommunity/GP2040-CE/assets/16499022/16eb72b7-e800-45c1-81b3-51f0327b9ee7)

When set, this label is added in each profile tab on pin mapping setting, and also on the profile selector on the settings page

![2024-01-19 07_29_43-GP2040-CE Configurator — Firefox Nightly](https://github.com/OpenStickCommunity/GP2040-CE/assets/16499022/68073c04-9f58-4216-bbdf-0020eb2676c3)

![2024-01-19 07_11_17-GP2040-CE Configurator — Firefox Nightly](https://github.com/OpenStickCommunity/GP2040-CE/assets/16499022/938e44a9-fab2-4ba5-8c87-8c9c54fd44bd)

I'm thinking also that the label should be limited to 5 ascii char (good enough imho: sf6, tk8, dbfz, shmup, base, etc.) and added on the display next to the profile number (feature wip: https://github.com/OpenStickCommunity/GP2040-CE/issues/688).

### Describe alternatives you've considered

None.

### Can you submit a pull request?

No

### Are you planning on working on this feature yourself?

No

**Comment by bsstephan** [comment]
@TheTrainGoes had an additional idea that we might as well put here: we could also use that label in the OLED.

This would be a fairly simple change, too --- I think you could just add the `name` or `label` as a field to `GpioMappings` and then refer to it in stuff. Seems like a neat idea.

**Comment by TheTrainGoes** [comment]
By my count there are 20 character lots on a normal 128x64 display.

Have two fields added in:
[Profile Name] 20 character limit
[Display time length when switching] done in seconds

**Comment by bsstephan** [comment]
I think this is my "up next".
