### ISSUE TITLE
Input history is not always accurate

### ISSUE THREAD

**Issue by Cnul971** [OpenStickCommunity/GP2040-CE#812]
* Firmware Version: GP2040-CE_0.7.7_Haute42.uf2
* Name of device: Haute42 S16
* Link to where you purchased the device: https://haute42.com/
* Is this a custom build?: no
* Operating System: windows 11
* Browser: Firefox

### Expected Behavior

I used the Macro add to do a quarter circle forward input fast and i expect to see those input display on the LCD

### Current Behavior

The input history drop some input when they follow them each other fast. But the game still recognize the macro well.
The game used is Ultra Street Fighter 4

### Steps to Reproduce

record a quarter circle with each direction last one frame and Post Input Wait Duration last 0 frame

### Screenshots & Files

![IMG_20240121_004754963_HDR](https://github.com/OpenStickCommunity/GP2040-CE/assets/157255289/989bfd73-e73d-4818-b873-4b1f31b4f1df)
![IMG_20240121_001810501_HDR](https://github.com/OpenStickCommunity/GP2040-CE/assets/157255289/d65535a0-e7fb-463a-afd8-446b6807f19b)
<img width="570" alt="Capture d'écran 2024-01-21 001855" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/157255289/e34be670-2bb0-49e5-8f35-c79172b339d7">

**Comment by bsstephan** [comment]
Unassigning this one from me, because what I found was more wondering aloud than a lead, so someone should take a look at this when they are interested.

**Comment by TheTrainGoes** [comment]
@Cnul971 can you please test this again when we release the v0.7.8 RC1 and tell us if its working any better?

**Comment by Cnul971** [comment]
@TheTrainGoes ok i will for sure !!! Thanks !!!

**Comment by Cnul971** [comment]
@TheTrainGoes tested with RC1, still the same problem (this time with SF6
![Capture d'écran 2024-04-03 002304](https://github.com/OpenStickCommunity/GP2040-CE/assets/157255289/439afeea-89d9-443a-9210-9113d8334a50)
![Capture d'écran 2024-04-03 001952](https://github.com/OpenStickCommunity/GP2040-CE/assets/157255289/ea1fe14b-dc26-4213-ac07-ec1b8e21bb0d)
![IMG_20240403_001937064](https://github.com/OpenStickCommunity/GP2040-CE/assets/157255289/7739d7b8-adf6-403f-8cf7-9f718fb8b603)

**Comment by Cnul971** [comment]
an other try
![IMG_20240403_002051492](https://github.com/OpenStickCommunity/GP2040-CE/assets/157255289/77cc6bb4-84ce-4c50-9037-06d672484082)
![Capture d'écran 2024-04-03 002100](https://github.com/OpenStickCommunity/GP2040-CE/assets/157255289/f6f18f7e-e6f4-46ba-9d51-1a32f7ba635c)

**Comment by TheTrainGoes** [comment]
@Cnul971 have you tested this out in v0.7.9?

**Comment by TheTrainGoes** [comment]
Closing - have not gotten word back.  If this is still an issue please file a new issue.
