### ISSUE TITLE
0.7.7 version has a simultaneous input issue

### ISSUE THREAD

**Issue by Arastoa** [OpenStickCommunity/GP2040-CE#819]
Hello.

I love to play FF THEATRHYTHM FINAL BAR LINE using haute42.

Here is 0.7.7 playing situation.
https://drive.google.com/file/d/1xakqKHuUCKsIADoDgochZJwVZsAgr6Pi/view?usp=sharing

and 0.7.6
https://drive.google.com/file/d/1sNzjOgGsKFUBsPpu4-emQqC_D7MxAkAC/view?usp=sharing

I think this problem is a gp2040-ce code issue.

**Comment by TheTrainGoes** [comment]
Hi @Arastoa ,

I am going to guess you are running in a mode that has SOCD on.  

Our SOCD filters will cause opposing inputs to be cleaned based on the currently selected SOCD rule.

If you are playing something like THEATRHYTHM FINAL BAR LINE I would recommend that you put it into an input mode that supports no SOCD cleaning.  This can be changed in the web-config.

That should resolve your issue.

There is no issue with the GP2040-CE code, it is functioning as intended.

**Comment by Arastoa** [comment]
I pushed triangle, square button.

I tested socd neutral and last win in 0.7.7. Nothing changed.

I think socd is not involved this situation.

**Comment by TheTrainGoes** [comment]
@Arastoa we will need some more info from you if the buttons pressed are not directional inputs.  

If you are on Discord can you please submit a support ticket there so we can have a more in-depth conversation?

If not, can you please tell us more about which controller you are using, which system this is occurring on, any special setups you have, etc.  

The videos you provided do not give us enough info.

**Comment by TheTrainGoes** [comment]
@Arastoa are you able to provide any more info on this?

**Comment by TheTrainGoes** [comment]
Closing due to lack of response
