### ISSUE TITLE
Enabling Reverse Input Button Breaks SOCD

### ISSUE THREAD

**Issue by tomatosoupcan** [OpenStickCommunity/GP2040-CE#822]
### Prerequisites

Please check the following before posting an issue / bug report.

- [x] I am running the latest version of the firmware found [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases)
- [x] I have checked the documentation [HERE](https://gp2040-ce.info/) and found no answer
- [x] I checked to make sure that this issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues)
- [x] I am reporting the issue to the correct repository

### Context

Please provide all relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.  

* Firmware Version: GP2040-CE : v0.7.7
* Name of device: SallyBox, Flatbox R1, etc.
* Link to where you purchased the device: https://fightboxarcade.com/collections/fightbox-r-game-controllers / https://www.aliexpress.us/item/3256805359350735.html
* Is this a custom build?: No
* Operating System: Windows 11
* Browser: Firefox / Chrome

### Expected Behavior

When turning on the addon for Input Reverse, pressing the button should reverse the input as defined in the reverse input rules. Additionally, existing functionality should not be impacted when this button/mode is active.

### Current Behavior

When the addon for Input Reverse is enabled, all SOCD modes break. All buttons can be held down at any time without SOCD cleaning. This is irrespective of the Input Reverse button being pressed.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Set SOCD cleaning mode to any mode other than "Off"
2. Reboot device and see that SOCD presses are properly handled
3. Enable a button for Input Reverse
4. Reboot device and see that SOCD presses are not properly handled

**Comment by TheTrainGoes** [comment]
Thank you for the report @tomatosoupcan ,

We are aware of this issue.
