### ISSUE TITLE
Bug - Keyboard mapping changes made in web-config not persisting on reboot

### ISSUE THREAD

**Issue by TheTrainGoes** [OpenStickCommunity/GP2040-CE#836]
### Prerequisites

Please check the following before posting an issue / bug report.

- [X] I am running the latest version of the firmware found [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases)
- [X] I have checked the documentation [HERE](https://gp2040-ce.info/) and found no answer
- [X] I checked to make sure that this issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues)
- [X] I am reporting the issue to the correct repository

### Context

Please provide all relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.  

* Firmware Version: v0.7.7 RP2040 Advanced Breakout Board with USB Passthrough
* Name of device: RP2040 Advanced Breakout Board with USB Passthrough
* Link to where you purchased the device: Made it
* Is this a custom build?: No
* Operating System: M1 Mac
* Browser: Tested in Chrome and Safari

### Expected Behavior

Changing the `Keyboard Mapping` to non-conflicting keys and hitting save should save those changes and be available on reboot to controller.

### Current Behavior

chaning the `Keyboard Mapping` to non-conflicting keys and hitting save shows saved and properly send a `SetKeyMapping` call (which contains the correct information) but this does not save through a reboot back to gamepad mode.  

While in the web-config, navigating around will show the changed key mapping however if you refresh web-config it will revert to the originally set key.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1 - Enter web-config
2 - Navigate to `configuration` and then `keyboard mapping`
3 - Change and of the mappings to non-conflicting keys
4 - Hit save
5 - Reboot to controller mode

`SetKeyMapping` shows a correct call when inspected:
A1
: 
38
A2
: 
59
B1
: 
225
B2
: 
29
B3
: 
224
B4
: 
226
Down
: 
81
Fn
: 
0
L1
: 
6
L2
: 
25
L3
: 
46
Left
: 
80
R1
: 
44
R2
: 
27
R3
: 
45
Right
: 
79
S1
: 
34
S2
: 
30
Up
: 
104

**Comment by bsstephan** [comment]
I think the keys are properly being set and saved in the config, and they are properly coming out of the API, but there's something odd with the webconfig UI loading the defaults. I...

1. called `getKeyMappings` to save a before state
2. did steps 1-4 above
3. rebooted back into webconfig mode
4. saw the defaults still
5. called `getKeyMappings` again, saw different values than before
6. went back to webconfig, changed one mapping (left to 'A' --- code 4)
7. saved, rebooted into controller mode
8. held left, saw 'a' spammed to my terminal
9. rebooted to webconfig
10. confirmed that webconfig mode showed Left as "Arrow Left"

So not as scary as it could been, and the device should work as desired, just you have to reconfigure it every time you're in the window until this is fixed.

**Comment by bsstephan** [comment]
This has been fixed as part of fixing #808, I believe.
