### ISSUE TITLE
Changing display layout in web config doesn't update display while in preview mode (pressing B1)

### ISSUE THREAD

**Issue by jack2game** [OpenStickCommunity/GP2040-CE#874]
### Prerequisites

Please check the following before posting an issue / bug report.

- [x] I am running the latest version of the firmware found [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases)
- [x] I have checked the documentation [HERE](https://gp2040-ce.info/) and found no answer
- [x] I checked to make sure that this issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues)
- [x] I am reporting the issue to the correct repository

### Context

Please provide all relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.  

* Firmware Version: Compiled from latest [main](https://github.com/OpenStickCommunity/GP2040-CE/commit/53099a722f1ed21f222825b75e32c56c218239a7)
* Name of device: -
* Link to where you purchased the device: -
* Is this a custom build?: -
* Operating System: Windows 11
* Browser: Chrome

### Expected Behavior

User should be able to preview current display layout by pressing B1 while in the web config, and when changing the settings in web config, the display will also change accordingly.

### Current Behavior

Changing display layout in web config doesn't update display while in preview mode (pressing B1)

**Comment by mikepparks** [comment]
Layouts in v0.7.8 will now update both by refreshing in webconfig (toggling between) as well as switching the mode while on the layout preview screen (new as of this release).  Furthermore, changing profiles will also cause the screen to refresh to show the new profile setting.
