### ISSUE TITLE
Keyboard mode issue 

### ISSUE THREAD

**Issue by SpongeAlan39** [OpenStickCommunity/GP2040-CE#882]
Using keyboard mode, it will always input twice quickly when I press any of the buttons. That's can only happen in keyboard mode. And I'm sure there is no problem with my bottons.

**Comment by arntsonl** [comment]
This should be resolved on the upcoming release, we had an issue with debouncing that will be fixed on 0.7.8.

**Comment by bsstephan** [comment]
Closing accordingly, please reopen if you continue to have this problem on 0.7.8 (and potentially after tweaking your debounce delay).
