### ISSUE TITLE
Please Add Joystick Selection Slider shortcuts to hotkey options

### ISSUE THREAD

**Issue by TheWarming** [OpenStickCommunity/GP2040-CE#888]
Like:  
Hotkey Settings
Fn + S1 = D-PAD MODE:  Right Stick      (not Dpad Right Analog)

I think it's more convenient to switch for the controller without slider.

**Comment by bsstephan** [comment]
Please read the documentation as this already exists. https://gp2040-ce.info/hotkeys/

**Comment by TheWarming** [comment]
> Please read the documentation as this already exists. https://gp2040-ce.info/hotkeys/

Please carefully read my instructions.
Fn + S1 = D-PAD MODE: Right Stick (not Dpad Right Analog)

Dpad right analog exists, but Joystick Selection Slider  doesn't .
 I want to hold down this button(like Fn + s1) to switch, and once released, it will revert back to D-pad.

**Comment by TheWarming** [comment]
> > Please read the documentation as this already exists. https://gp2040-ce.info/hotkeys/
> 
> Please carefully read my instructions. Fn + S1 = D-PAD MODE: Right Stick (not Dpad Right Analog)
> 
> Dpad right analog exists, but Joystick Selection Slider doesn't . I want to hold down this button(like Fn + s1) to switch, and once released, it will revert back to D-pad.This way, there is no need to switch back to D-pad through shortcuts again. I am not good at english. Hope you can understand what i want

**Comment by TheTrainGoes** [comment]
Hi @TheWarming ,

This was read carefully, your initial comment was not clear.

This is not something we are looking to implement at this time.
