### ISSUE TITLE
How to compile the version of haute42 of 0.7.7?

### ISSUE THREAD

**Issue by okabesg** [OpenStickCommunity/GP2040-CE#902]
### Expected Behavior

I expect to get a GP2040-CE_0.7.7_haute42.uf2 file

### Current Behavior

I clone the repo and switch to the Haute42 branch, which called 20240115-Haute42-update. After that, I create the build dir and run 
`cmake ..` 
and
`make`.
But all I got was GP2040-CE_0.7.6_Pico.uf2 file, which is the wrong version.
How to fix this? Thanks a lot!

### Screenshots & Files

<img width="341" alt="be683ff53771f24c68af5c4f454cf48" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/24471603/ad3aa310-4139-4f93-bfd5-b6a0c7de59dd">

<img width="462" alt="f89131037499121a7236789cbe839a5" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/24471603/f2897260-4b41-43a8-868d-07ba2d49daf3">

**Comment by Pelsin** [comment]
This is working as intended and is not a bug.
Please read through the documentation for firmware development: https://gp2040-ce.info/development/firmware-development and the documentation in general for these types of questions.

The default board config to use is pico: https://gp2040-ce.info/development/firmware-development#building

A haute config also exists in main or an artifact in the latest release, would be better than using a stale branch.

If you have question, you are welcome to join the discord.

**Comment by okabesg** [comment]
The documentation works for me! Thank you so much!
I'm new here and didn't know how to find useful infomation in the documentation.
Thanks again!
