### ISSUE TITLE
Bounty - SHMUP mode

### ISSUE THREAD

**Issue by TheTrainGoes** [OpenStickCommunity/GP2040-CE#93]
Currently people who enjoy SHMUPS cannot use the charged shot feature if turbo is enabled on a the same button.  

This requires the person to either turn off turbo to do a charged shot or assign another button in game to be a secondary shot button (not available in all games).

This bounty is to add a dedicated SHMUP section to the add-ons page which allows for the following:

1 - Ability to set an always-on turbo to a specific button or GPIO (this eliminates the need to set it on every reboot)
2 - Ability to set an additional instance of a button to a GPIO pin that would not be impacted by turbo

As a bonus

3 - Ability to have a pot or rotary dial setup which can be used to adjust the speed of the turbo on the fly without the need for shortcuts.

**Comment by arntsonl** [comment]
All 3 requests are covered:

1 - Ability to set an always-on turbo to a specific button or GPIO (this eliminates the need to set it on every reboot)
** 4 always-on turbo button masks are now available in SHMUP mode

2 - Ability to set an additional instance of a button to a GPIO pin that would not be impacted by turbo
** 4 charge shot (never turbo) button masks are now available in SHMUP mode

** Mixing priority is also available if a user inputs charge and non-charge turbo at the same time

As a bonus

3 - Ability to have a pot or rotary dial setup which can be used to adjust the speed of the turbo on the fly without the need for shortcuts.
** Done! Tested using a 10k potentiometer, requires using Pins 26-28 for the ADC reader
