### ISSUE TITLE
7.8 RC1 Macro bug

### ISSUE THREAD

**Issue by wesleysni** [OpenStickCommunity/GP2040-CE#930]
### Expected Behavior

> When using 
![Screenshot 2024-04-02 124340](https://github.com/OpenStickCommunity/GP2040-CE/assets/77167161/2b179b7a-d72a-4890-806e-94ab1b953650) 
Macro Activation Type : Hold Repeat

Prior to upgrade to 7.8 It is supposed to run the macro while pin is held down, then stop when released. 

### Current Behavior

When activating macro pin, macro repeats but does not stop when releasing macro pin. (Worked properly in 7.7)

### Context

Version
RP2040 Advanced Breakout Board (GP2040-CE_0.7.8_RP2040AdvancedBreakoutBoard.uf2)

Current: v0.7.8-RC1

Latest: v0.7.7

Memory (KB)
Flash: 913.87 / 2048 (44.62%)
Heap: 14.69 / 152.09 (9.66%)

Static Allocations: 111.91

os: windows 10
webbrowser: google chrome

### Steps to Reproduce

I upgraded from 7.7 to 7.8
Macros and all other settings were programmed on 7.7 and carried over to 7.8 after upgrade
After upgrade I tested this in Street Fighter 6 
Activate macro and it repeats continuously without being able to stop (until i unplug controller)
I will provide pictures below

### Screenshots & Files

![Screenshot 2024-04-02 124409](https://github.com/OpenStickCommunity/GP2040-CE/assets/77167161/b699ab0d-d03e-4314-839f-667d70adb83b)
![Screenshot 2024-04-02 124414](https://github.com/OpenStickCommunity/GP2040-CE/assets/77167161/501e3a18-8078-47b9-b3fa-d1fea570525d)
![Screenshot 2024-04-02 124401](https://github.com/OpenStickCommunity/GP2040-CE/assets/77167161/bcb09e6c-e202-4e78-9998-464a8bb32375)
![Screenshot 2024-04-02 125453](https://github.com/OpenStickCommunity/GP2040-CE/assets/77167161/dac2d8db-901c-4528-9465-31b9b2d1c7e2)

**Comment by arntsonl** [comment]
Perfect, thank you for all of the details! We'll get this replicated and figured out.

**Comment by wesleysni** [comment]
I also nuked then flashed to 7.8 and problem still persists as well.

**Comment by arntsonl** [comment]
Should be fixed in RC2. Will verify on full release and close.

**Comment by TheTrainGoes** [comment]
This has been addressed in release + hot fix
