### ISSUE TITLE
Haute42 g16 rgb led not working after reset

### ISSUE THREAD

**Issue by DarkSim0** [OpenStickCommunity/GP2040-CE#935]
Hi all my g16 haute42 rgb lighting is not working i tried installing the firmware again but still not working i also tried following the same config in the docs page no improvement either please help

**Comment by TheTrainGoes** [comment]
Hi @DarkSim0 , 

Please join up in their Discord and submit a support ticket there.  

https://discord.com/invite/hcCyQRffbU
