### ISSUE TITLE
Logitech pedal how to configure properly

### ISSUE THREAD

**Issue by manotroll** [OpenStickCommunity/GP2040-CE#948]
I made the connections and put it to use the analogue and disabled all the other pins but it was varying a lot and I still tried to calibrate it without success
My idea is to use just the 3 pedals or should I ground all the other pins even setting them to none

**Comment by bsstephan** [comment]
I'm closing this because this is not formatted clearly as an issue or feature request, and driving/wheel stuff is currently outside of the scope of this project.

**Comment by manotroll** [comment]
My question is how to use 3 analogues
