### ISSUE TITLE
Macro frames bugs

### ISSUE THREAD

**Issue by rebornsick** [OpenStickCommunity/GP2040-CE#960]
> Please read these quoted sections before submitting, and remove them (including this one) when you have provided what
> is asked, in order to make addressing the issue easier for everyone. Thank you!
>
> Be sure to:
> * Check the documentation [HERE](https://gp2040-ce.info/) to answer many questions on firmware capabilities and usage.
> * Make sure that your issue has not already been filed [HERE](https://github.com/OpenStickCommunity/GP2040-CE/issues).
> * Confirm your issue exists on the latest version of the firmware, found
  [HERE](https://github.com/OpenStickCommunity/GP2040-CE/releases).

### Expected Behavior

Each action in the settings lasts the same number of frames

### Current Behavior

In Street Fighter 6

- frames for every action doesn't work
- after reboot device many times for testing macro settings, can't save in macros configuration

### Context

- Flashed nuke firmware
- flash latest 0.7.8.pico firmware
- disable turbo add-on
- setup maros
- change pin mapping

### Screenshots & Files

<img width="549" alt="Snipaste_2024-04-11_18-03-12" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/28842872/2e4a1067-2932-4ad4-b9a1-6aba1b9291b5">
<img width="105" alt="Snipaste_2024-04-11_18-02-20" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/28842872/45f76682-6abf-4f4a-890b-46a79e2c56d2">

**Comment by TheTrainGoes** [comment]
Hi @rebornsick ,

To ensure I am understanding this correctly, you are expecting that "Each action in the settings lasts the same number of frames" despite it being listed as different numbers of frames in the attached screenshot?

Have you attempted to do this via MS settings and play around with those at all?

**Comment by rebornsick** [comment]
Hi @TheTrainGoes ,

I mean no matter what number of frames I set, macros only take 1 frame for every action.

I tested both 0.7.7 and 0.7.8 with only changing macro configs and mapping the same macro button, 0.7.7 works as I expected and 0.7.8 only takes 1 frame as you see. (1, 2, 3, 4, 5 frames for 5 actions)

<img width="102" alt="Snipaste_2024-04-11_20-43-23" src="https://github.com/OpenStickCommunity/GP2040-CE/assets/28842872/f15e3a0d-b5d7-4ca0-807f-b58202f08aca">

**Comment by TheTrainGoes** [comment]
@rebornsick are you able to replicate this in MS mode (opposed to frames)?

**Comment by rebornsick** [comment]
@TheTrainGoes MS means millisecond？yeah it's same.

**Comment by TheTrainGoes** [comment]
@rebornsick so you changed it to MS, made adjustments and the firmware is not respecting those adjustments?

**Comment by rebornsick** [comment]
@TheTrainGoes yes, it's same, only 1 frame. So you can't replicate this? does this relate to hardware? I'm using haute42 S16 but with pico firmware though

**Comment by rebornsick** [comment]
@TheTrainGoes OK, this doesn't affect me much, just letting you know.Thanks for your work 🫡

**Comment by rebornsick** [comment]
@TheTrainGoes Hello, I just noticed that we re-compiled 0.7.8 firmware and it fixed this frame bug.

**Comment by TheTrainGoes** [comment]
Hi @rebornsick ,

Yes, this is addressed now and I will close the ticket off.
