### ISSUE TITLE
Stick display is flickering when neutral SOCD is active in 0.78

### ISSUE THREAD

**Issue by renzeiron** [OpenStickCommunity/GP2040-CE#966]
### Expected Behavior

Stick display returns and stays in the neutral position when neutral SOCD is active, as it was in the version 0.77 of the firmware.

### Current Behavior

As of 0.78, stick display is flickering when neutral SOCD is active. See the video below.

### Context

* Firmware version: 0.78
* Board config: Haute 42 (GP2040-CE_0.7.8_Haute42.uf2)
* Device: Haute42 T16 
* Purchased from the official Haute42 store at AliExpress

### Steps to Reproduce

* Go to the Gamepad Settings page
* Make sure that SOCD Cleaning Mode is set to Neutral
* Go to the Display Configuration page
* In the Layout Options category choose "Stick" as one of the layouts
* Save and reboot the device
* Activate SOCD cleaning by pressing up and down or left and right simultaneously

### Screenshots & Files

https://github.com/OpenStickCommunity/GP2040-CE/assets/20214248/e1ff2c6a-2b17-4a6d-bdfe-82ee7edc8234

**Comment by bsstephan** [comment]
@renzeiron This has been fixed and will be in the next release of the firmware.
