### ISSUE TITLE
Dual Directional Enabled with NO pins causes reverse inputs

### ISSUE THREAD

**Issue by arntsonl** [OpenStickCommunity/GP2040-CE#97]
We had to hot-fix this in 0.6.1

It looks like dual directional enabled with no pins assigned causes the dpad to reverse up and down.

**Comment by Soundtoxin** [comment]
I just hit this flashing a new Flatbox rev5. I see the recent commit to fix it, but is it not in a release yet? When will it be in a release?

**Comment by TheTrainGoes** [comment]
This has been fixed - thanks @arntsonl !
