### ISSUE TITLE
GPIO pins used for internal board functions are still mapable in the pin mapping page

### ISSUE THREAD

**Issue by looper1234** [OpenStickCommunity/GP2040-CE#981]
Problem
![image](https://github.com/OpenStickCommunity/GP2040-CE/assets/10213191/a951b0fc-f8f4-4610-9fb8-ece594533f47)
these pins are not available to end users 

but the pin mapping page lead me to believe pins such as 25 and 29 can be used for extra buttons

Solution

leave only the usable/customisable pins in the mapping page, and perhaps a brief reason why some pins are missing

**Comment by TheTrainGoes** [comment]
@looper1234 This is heavily dependant on what device you are using.  If you are using a Pico those pins are reserved but if you are using a raw RP2040 you can have them used for other functions.  

@bsstephan will chat with you about this one.

**Comment by TheTrainGoes** [comment]
This has been addressed and used pins are now block out on the configs that we support.

We cannot account for devices that are used outside of the supported ones.
